### PR TITLE
Added parameters to improve (PRESSURE) results when compared to Eclipse.

### PR DESCRIPTION
**Pull request by flikka**
After f007bf561cb07e4a0cb10534661be647eb13ecef the default parameters were changed, and the results for SPE tests diverged a bit more from Eclipse. This commit brings them back to where they were.

### CODE REVIEW

**Comment by atgeirr** [comment]
I am honestly a little surprised that you got back the original results (or close) with so few changes. Thanks for reporting and fixing.

**Comment by flikka** [comment]
@atgeirr - with good reason. I had my eyes on the PRESSURE output, but as it turned out, there were some more deltas left (SGAS). Will look at it, and update accordingly.

**Comment by totto82** [comment]
Adding a few time steps after 360 days also does the trick .  Then you can even use AMG

for instance changing from 
5 10 10 15 20 /
to
1 4 10 10 10 15 /

**Comment by atgeirr** [comment]
I think that the SPE tests should use the same options and timesteps that they have been using so far (just need to provide them as they are no longer defaults). That way we have better continuity. To test these cases using different options (esp. adaptive timestepping) I would rather set up additional, new tests.

**Comment by totto82** [comment]
Sounds like a good plan. We could for instance make a spe9_regression_test1.param with the old default values.

**Comment by flikka** [comment]
New PR: https://github.com/OPM/opm-data/pull/43

Was a bit unsure what to set  max_residual_allowed and tolerance_wells to, so I left them out. If they should be set too, I can amend with proper values (please supply).

**Pull request merged**
