### PR TITLE
Eclipse output for SPE1

### PR DESCRIPTION
**Pull request by flikka**
Renamed deck file - added output from Eclipse run.

### CODE REVIEW

**Comment by andlaus** [comment]
ouch. eclipse expects all-uppercase filenames?

**Comment by flikka** [comment]
AFIK, yes, at least it did not work here in Statoil without :-). Gotta love it.

**Comment by alfbr** [comment]
Actually, I believe that depends on how you submit the job. I used lower case a few years back on a project, but since it is rather fragile, I try to stick to upper case.

**Comment by bska** [comment]
> eclipse expects all-uppercase filenames?

Yes--well at least the file name **extensions** must be upper case.  Of course, this is strictly speaking dependent on the filesystem implementation.  On case-insensitive systems you can name your files using lower-case names whereas you're better off using upper case on case-sensitive or case-preserving systems.

**Pull request merged**
