### PR TITLE
Update data for regression tests

### PR DESCRIPTION
**Pull request by akva2**
This
- adds some reference data sets for norne, for flow and eclipse
- updates the reference data for SPE1CASE2 (apparently output from flow has changed since they were generated).

Replaces #124

### CODE REVIEW

**Comment by alfbr** [comment]
Actually, I thought the restart files were to large for github, but they appear to go through. Great! We do miss the git commit hashes for the opm-reference, but they are maybe not available? If not, I am ready to merge this.

**Comment by akva2** [comment]
ah, they were only attached to the pull request and not the commit. will remedy. there is no restart data from eclipse in here, ref #124

**Comment by joakim-hove** [comment]
> apparently output from flow has changed since they were generated

Probably - and it will continue to do so; I fear this will be a high-maintenance solution.

**Comment by alfbr** [comment]
> Probably - and it will continue to do so; I fear this will be a high-maintenance solution.

Are you proposing that we do not monitor changes in simulation results?

**Comment by alfbr** [comment]
Thanks for the hashes, merging this now. I can update results if there are any fall-outs.

**Pull request merged**
