### PR TITLE
Added SPE-cases with copyright Statoil

### PR DESCRIPTION
**Pull request by larsblatny**
Added SPE1. Case 1 and 2 in one file, comment out two lines to get Case 1 as explained in code.
Added SPE3. Case 1 and 2 in separate files.

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the good work! Please remove STATOIL from the file names. While STATOIL currently holds sole copyright, this changes when a non-Statoil employee commits changes to the files. Hence it does not make sense to include current copyright holder in the filename.

**Comment by atgeirr** [comment]
Great! Just some comments/questions:
- Have you run this with ECLIPSE? Reproducing expected results?
- Can this be run with Flow? I think we do not support all the keywords used here, but I am not quite sure. Have you tried?
- The comments you have made in the file should be quite helpful to anyone playing around with this, good!

**Comment by alfbr** [comment]
Please also split SPE1 into two cases, indicating case in filename.

**Comment by larsblatny** [comment]
The keywords used should be supported by Flow, with the exception of those used in the SUMMARY section. All the files will run with both Eclipse and Flow, and the following can be noted:

Running the SPE1-code with Eclipse will result in graphs very similar to those in the SPE-paper (only very small deviations). Note that I have only compared the graphs with time as x-axis. Running the code with Flow will result in graphs that are not consistent with the SPE-paper/Eclipse.

The SPE3-code seems to produce the expected results with Eclipse: Graphs of oil production rate and oil production total are consistent with the SPE-paper graphs. However, the graph of oil saturation in block (7,7,4) could have matched the expected result better, but this might change when/if I receive updated PVT data. With Flow, the graph of oil production rate will be fairly similar to the SPE-paper graph, but the oil production total is different. In general, there are similarities and differences between Eclipse and Flow.

**Comment by larsblatny** [comment]
I will change the names and split the files, I will do it tomorrow morning!

**Comment by alfbr** [comment]
Do not remove copyright notice from the file, only company name from file name. Future copyright holders will typically be added as we move along.

**Comment by alfbr** [comment]
Thank you! Merging.

**Comment by atgeirr** [comment]
With this, I think we should take the SPE1 and SPE3 cases to the opm-autodiff module as tests, that are automatically run by `make test` (perhaps shortened versions to keep time to a few seconds each if people are annoyed by longer test times). The question is how to do it properly, we could recycle the comparison scripts used on Jenkins for example.

**Comment by akva2** [comment]
if the comparison script is "properly" written, it should work fine as the driver in opm_add_test().

**Pull request merged**
