### PR TITLE
update the UNSMRY file for the OPM reference solution

### PR DESCRIPTION
**Pull request by andlaus**
this one changed because the current master only writes at the end of
each report step instead of at the end of each time step plus at the
end of each report step as it used to be. the curves seem to be
identical when ajusting for this, i.e. they touch at what seems to be
the end of report step.

this is how a typical curve looks like:

wbhp b-2h

### CODE REVIEW

**Comment by atgeirr** [comment]
Is this using this morning's master, or does it include opm-material#142? I'd like to wait a little bit before merging this, to make sure we are merging the right thing. Also: are the summary files small enough to consider keeping a sequence of them for posterity?

**Comment by atgeirr** [comment]
One more: is this not used by the Jenkins comparison job? If so, that may need to change due to the updated path.

**Comment by andlaus** [comment]
> Is this using this morning's master, or does it include opm-material#142?

yes, it includes opm-material#142. That said, without a microscope it is impossible  to spot a difference in the curves between the master versions before and after it.

> I'd like to wait a little bit before merging this, to make sure we are merging the right thing.

agreed. I'd just like the reference solution that is provided with the release to be consistent with what the released binaries produce. (currently they are not -- and have not been for a while.)

> Also: are the summary files small enough to consider keeping a sequence of them for posterity? 

in the case of Norne the newer UNSMRY files are about 480kB, the old one was about 1.2 MB. you decide whether it is small enough.

I'd prefer to remove the old files to avoid confusion, though...

> One more: is this not used by the Jenkins comparison job? If so, that may need to change due to the updated path.

I don't actually know if it is used. I know that the restart file of SPE-1 is compared but I doubt that summary files are compared at all (updated  path or no). @akva2: can you enlighten us?

**Comment by akva2** [comment]
For norne the only output is the graph. There is no reference data used for comparison. Ref opm-simulators/jenkins/run-norne.sh and opm-data/norne/plotwells.sh

-------- Opprinnelig melding --------
Fra: Andreas Lauser notifications@github.com
Dato: 19.04.2016 21:45 (GMT+01:00)
Til: OPM/opm-data opm-data@noreply.github.com
Ko: Arne Morten Kvarving Arne.Morten.Kvarving@sintef.no, Mention mention@noreply.github.com
Emne: Re: [OPM/opm-data] update the UNSMRY file for the OPM reference solution (#99)

Is this using this morning's master, or does it include opm-material#142?

yes, it includes opm-material#142. That said, without a microscope it is impossible to spot a difference in the curves between the master versions before and after it.

I'd like to wait a little bit before merging this, to make sure we are merging the right thing.

agreed. I'd just like the reference solution that is provided with the release to be consistent with what the released binaries produce. (currently they are not -- and have not been for a while.)

Also: are the summary files small enough to consider keeping a sequence of them for posterity?

in the case of Norne the newer UNSMRY files are about 480kB, the old one was about 1.2 MB. you decide whether it is small enough.

I'd prefer to remove the old files to avoid confusion, though...

One more: is this not used by the Jenkins comparison job? If so, that may need to change due to the updated path.

I don't actually know if it is used. I know that the restart file of SPE-1 is compared but I doubt that summary files are compared at all (updated path or no). @akva2https://github.com/akva2: can you enlighten us?

**Comment by andlaus** [comment]
can this be merged before the release, please? If it is insisted uppon, I'll provide a file which is produced by the current master versions. (although I bet that there's no difference in the first 6 decimal digits or so.)

**Comment by atgeirr** [comment]
> can this be merged before the release, please? If it is insisted uppon, I'll provide a file which is produced by the current master versions.

I'll leave this decision to @totto82.

**Comment by alfbr** [comment]
Sure, thanks for the update.

**Comment by alfbr** [comment]
My apologies, I was not informed that OPM now does the regression checks on its own results, and hence this needs to be tested before merging. Moreover, I really dislike the folder renames, it triggers unneeded maintenance on our Jenkins server. Please create a new PR with (a more) generic name on folder.

**Comment by akva2** [comment]
actually it doesn't trigger any maintenance on the jenkins side. the path that missed the update is in the script which sits in opm-data (plotwells.sh). i did (try to) point this out before things was merged. the updates on jenkins is me adding triggers in opm-data to make it easy to test things before merging. now i need to wait for the next update, so when that pr lands, please let me use it to get things working first.

**Comment by alfbr** [comment]
I misunderstood your comment. We need to have a walk-through on this set-up once the dust settles on the release. Still, unless there are strong objections, we should go with a more generic name than a full date, anybody can check dates with git. I also suggest only one folder for simplicity. Name it OPM-reference-simulation and we can expand it later with more results than the summary output.

**Comment by akva2** [comment]
no objections there. i can do it if you want.

**Comment by alfbr** [comment]
Highly appreciated :-) please go ahead.

**Comment by joakim-hove** [comment]
> we should go with a more generic name than a full date, anybody can check dates with git

I was the one introducing the date based path names; the motivation was that I thought that for comparison it would be interesting to have several reference solutions present simultaneously - that is not easily possible with only git operations; then you can obviously only have one version in your working copy at a time. But no no strong feelings - if it is not perceived as valuable it should of course be removed.

**Comment by joakim-hove** [comment]
> Name it OPM-reference-simulation

That could be a symlink?

**Comment by alfbr** [comment]
> That could be a symlink?

Yes, but I am still in the dark as to the benefit of making this any more complicated than a simple self explanatory folder.

**Comment by joakim-hove** [comment]
> but I am still in the dark as to the benefit of making this any more complicated than a simple self explanatory folder.

As I said - I will not argue this; but one obvious advantage is that you can easily do comparisons between different versions of the reference solution - and see how it has evolved. Since these are binary files `git diff` will not give much in that respect.

**Comment by akva2** [comment]
while i see your point @joakim-hove it would in effect introduce the same problem as earlier, but in a different flavour and a more dangerous one at that. people will easily miss updating the symlink, thus running against an old reference and not the new one they just pushed and everything will appear fine unless you look at the details. the devil loves hiding there..

**Comment by alfbr** [comment]
> you can easily do comparisons between different versions of the reference solution - and see how it has evolved

I see, yes that is true. However, you can with relatively little effort get those with `git checkout`, so I do not see that it warrants the added complexity.

**Comment by joakim-hove** [comment]
> so I do not see that it warrants the added complexity.

Fine

**Comment by andlaus** [comment]
> actually it doesn't trigger any maintenance on the jenkins side. the path that missed the update is in the script which sits in opm-data (plotwells.sh). i did (try to) point this out before things was merged. the updates on jenkins is me adding triggers in opm-data to make it easy to test things before merging. now i need to wait for the next update, so when that pr lands, please let me use it to get things working first.

Seems like I misinterpreted you: I thought you said that the UNSMRY file was completely unused by all automated scripts and only provided for manual inspection purposes. Sorry.

> no objections there. i can do it if you want.

cool. I was just about to do this, but I'll happily hand this over to you :)

> That could be a symlink?

personally, I don't mind. My experience with symlinks in git on Windows is not the best, though.

**Comment by akva2** [comment]
yes i can see that it could be confused, but what i said is that there is no comparison apart from the graph. the graph is produced from eclipse reference data, opm reference data and the new run.

**Pull request merged**
