### PR TITLE
Updated SPE9_CP opm-simulation-reference

### PR DESCRIPTION
**Pull request by kristfho**
opm-common: hash `7f1716b9a6fa71ed6d48b7e71e464de0e66bab4e`
opm-parser: hash `948ed84ebc114163bccc1a8b3821ede2fc0cd593`
opm-material: hash `44fe774cfe69ae47d7952c4329df2e6cc3d8b4d1`
opm-output: hash `3fd5521d1dc3b97821e0cb136385d8948968f465`
opm-core: hash `dae94b504189e7fb7321d7f660ee979ee38e77fb`
opm-grid: hash `7e7748903ca789cdfa160346db15b32e8085c285`
opm-simulators: hash `e7213411de89c1217b987c8a7c9b3d83b5e865f8`

### CODE REVIEW

**Comment by joakim-hove** [comment]
What is the percieved workflow behind this? Of course embedding all these sha's in the commit message will give the ultimate reproducability - but how do you envison this actually being used?

**Comment by akva2** [comment]
I requested those because it is at times very important to be able to reproduce reference data. Sometimes the reference is what is broken and if i cannot tell what created the reference it is very hard to track such a situation.

**Comment by alfbr** [comment]
Where are the restart files?

**Comment by kristfho** [comment]
There were no changes in the restart files with respect to the already existing opm-simulation-reference. When running `git status` after `newlyDownloadedOpm/opm-simulators/build/bin/flow ~/opm-data/spe9/SPE9_CP.DATA`, the only files which were modified (and traced) were the three files which I commited.

**Comment by joakim-hove** [comment]
> Sometimes the reference is what is broken and if i cannot tell what created the reference it is very hard to track such a situation.

OK - fair enough; for this particular project we will for the foreseeable future have easy access to a "truth generator" to aim for; what you are gaining with this is extremely good opm - opm reference tracking, which is of course fine, but maybe not that interesting? Anyway - I'll shut the f... up.

**Comment by alfbr** [comment]
The restart files are also there AFAIK. For simplicity, I suggest we ensure that all files come from the same reference simulation.

**Comment by alfbr** [comment]
> what you are gaining with this is extremely good opm - opm reference tracking

You gain a starting point for bisection, something that has been sourly missing.

**Comment by joakim-hove** [comment]
> The restart files are also there AFAIK. For simplicity, I suggest we ensure that all files come from the same reference simulation.

I guess what has happened here is that due to updates in opm-output / opm-parser both the .INIT file and the summary files have been updated with new content, and git obviously detects the change. There have been no changes to the restart files, so by construction git has nothing to add.

**Comment by alfbr** [comment]
Ah, so the restart files have been updated, but they are identical? With a confirmation on that @kristfho I am ready to merge.

**Comment by kristfho** [comment]
By running `diff` ( ex: `diff ~/opm-data/spe9/opm-simulation-reference/SPE9_CP.UNRST ~/newFlowDownload/opm-data/spe9/opm-simulation-reference/SPE9_CP.UNRST`) on the new and old files, there are no output when comparing the `.UNRST` and `.EGRID`. The `.SMSPEC`, `.UNSMRY` and `.INIT` give the output `differ.`. 

`cmp` gives the same result as `differ` . 

If it is sufficient that `differ` say they are identical, so do I.

**Comment by alfbr** [comment]
Yes, diff suffices for that usage on binaries too :-) merging.

**Pull request merged**
