### PR TITLE
Added file: NORNE_ATW2013.UNSMRY

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by atgeirr** [comment]
To be sure: this file is created by running Eclipse on the deck from the same directory, in its current version? Also which version of Eclipse did you run?

**Comment by joakim-hove** [comment]
This is the UNSMRY file which we received for testing purposes a long time ago; I have not simulated this myself. According to the .PRT file version 2012.1 of Eclipse is used.

**Comment by dr-robertk** [comment]
I'm not sure if this is the correct one then, since the NORNE data set was recently changed. 
I can upload a 2014.2 simulated version with the current data set.

**Comment by GitPaean** [comment]
I think a new running is better. I could not find a lot of information from the current summary file. 

Looks like only WWIR for several wells. I am not 100 percent sure though. 

I am not sure whether we should use 2014.2 or 2013.2.

**Comment by dr-robertk** [comment]
I'm sure that I will use 2014.2, because that's the only version I have installed ;-)

**Comment by GitPaean** [comment]
That is good. For some other type simulations, I noticed Eclipse 2014.2 changed some of the formulations, the results are supposed to change in some way.

I am not sure if they changed anything related to our project. Anyway, other people can suggest the version of the Eclipse for reference solution.

**Comment by dr-robertk** [comment]
Good to know, I'll mark the file accordingly.

**Pull request merged**
