### PR TITLE
First open version of opm-data

### PR DESCRIPTION
**Pull request by alfbr**
The three commits making up this PR should be self-explanatory. I included a tag named proprietary so that you can easily access all decks with _git checkout tags/proprietary_. There are a couple of gotchas you need to be aware of outlined below.

@totto82 please consider reviewing this PR.

@andlaus please consider re-basing spe1_large on the new spe1 case.

@totto82 please consider re-basing the spe1_thermal on the new spe1 case.

simplespe1 is gone, but I am not sure it serves a purpose anymore. Please re-base it on the new spe1 case if you see it differently.

I will rerun the simulations to add reference solutions, those are lacking now. The comparative Jenkins jobs will need to be updated when this is in place, so expect some breakage there.

@totto82 the new SPE1 decks cover both published cases, whereas the old one only covered CASE2. Since DRSDT is not supported by OPM, you cannot expect correct results on CASE1 now. Hence consider basing the relative permeability test decks on CASE2 instead (simply commenting out DRSDT suffices).

### CODE REVIEW

**Comment by totto82** [comment]
Thanks for cleaning opm-data
I have tested the open SPEs and current status is: 
SPE1CASE1 (poor match, missing support for DRSDT)
SPE1CASE2 (good match)
SPE3CASE1-2 (ok match, some discrepancy in the water production curves)  
SPE9 (poor match, needed to use corner point grid to get match) 

I suggest the following: 
1) Add temporary warning in top of the SPE1CASE1.DATA that DRSDT is not supported in flow. 
2) Either  
   1) Add temporary warning in top of the current SPE9.DATA that there is a bug when Cartesian grid is used and  add a corner point version of SPE9.
   2) Just change the Cartesian input to corner point in the current SPE9 deck

**Comment by andlaus** [comment]
OPM/opm-autodiff#464 could also be involved in causing the difference of SPE1CASE1. (also, could you please check if the results for this case match if you remove DRSDT?)

**Comment by totto82** [comment]
@andlaus SPE1CASE2 is SPE1CASE1 where DRSDT is removed. Both of them uses EQUIL initialization.

**Comment by totto82** [comment]
In order to get the same result for SPE9 as the old deck. I had to hard-code the transmissibility factor using record 8 in Compdat and use corner-point input

**Comment by alfbr** [comment]
Thanks for the review! Notes added to both decks. Working on providing a SPE9 deck with cornerpoint geometry in a separate PR.

**Comment by totto82** [comment]
I will merge this now. But note that we will then not have a version of SPE9 that we support until @alfbr provides a SPE9 deck with cornerpoint geometry.

**Pull request merged**
