### PR TITLE
update reference data for spe1 spe9

### PR DESCRIPTION
**Pull request by akva2**
reason: https://github.com/OPM/opm-output/pull/136

ert            = dfb052ab287b1a268c541607f8ba50f715794b73
opm-common     = 2ddb6ac8c24d421a777f06ff5b09b83844e365f2
opm-core       = 1e462f4c044d393c59ef8b8b6d89e960447b1248
opm-grid       = 47743566b495e6d259b878efa02df6ea49f14d77
opm-material   = ee7737a97dec6115b55dc744e7df354d6772481c
opm-parser     = d6f6e2ca814ff166f60570407ea09a10af92d1eb
opm-output     = dab31ecda8347ad291872cfae318bbe7b1bd53d3
opm-simulators = 54ad92ff403ac2522cd4d90cb1725002fa81f1c3

### CODE REVIEW

**Comment by joakim-hove** [comment]
OK - this is [green on Jenkins](http://80.240.129.131:8080/job/opm-output-PR-builder/20/console) now; but strictly speaking the opm-output repo has recieved one additional commit: https://github.com/OPM/opm-output/pull/136/commits/f34678f18dd4f1652db19bff192e47ba34a41a4f - please merge both this and https://github.com/OPM/opm-output/pull/136 together; or alternatively update the commit message of this PR first.

**Comment by joakim-hove** [comment]
Unless there are objections I will merge this and OPM/opm-output#136 this afternoon.

**Comment by joakim-hove** [comment]
OK: Due to conflicts it was necessary to rebase https://github.com/OPM/opm-output/pull/136. This should not change the reference data in this PR, but of course the sha for opm-output has become invalid.

Please advise on the next steps.

**Comment by bska** [comment]
> Please advise on the next steps.

Put accurate commit IDs in the merge commit log?

**Comment by akva2** [comment]
if you are 100% output is the same, give me the new hash and i'll amend the commit message.

**Comment by joakim-hove** [comment]
> if you are 100% output is the same, give me the new hash and i'll amend the commit message.

OK - new sha:  dab31ecda8347ad291872cfae318bbe7b1bd53d3

**Comment by akva2** [comment]
done.

**Comment by joakim-hove** [comment]
> done.

Thank you.

**Pull request merged**
