### PR TITLE
update reference data for spe11 spe12 spe3 spe1-2p spe5 spe9 spe9group msw_2d_h simple2d

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: https://github.com/OPM/opm-grid/pull/284

libecl         = df165c1be3b0f6f74e4acaf07bf9f6776164fbd3
opm-common     = e6e5491c74a9ce05194391acc5e12218c846da95
opm-core       = 33305c4f1f31ee717e9709ecdfa87601ddc10c0a
opm-grid       = 1704d901c3383a22ea68472a3326fe56200e5cc4
opm-material   = c86c119120e88e8f26a64e5763a6781b0f9383e7
opm-parser     = e19fbec7736fb24c50a84e440fed87ae54a4b97a
opm-output     = 4c75f39866bc05d08c5b9cb9453b4575598de789
ewoms          = 3ecf500b495e8baf82903b34c3ae1627ccc44fa5
opm-simulators = 1704d901c3383a22ea68472a3326fe56200e5cc4

### CODE REVIEW

**Comment by GitPaean** [comment]
With dune-2.4.1, this PR caused the following failure in opm-simulators. 
```
The following tests FAILED:
	 21 - compareECLFiles_flow_ebos+SPE1CASE2 (Failed)
	 28 - compareECLFiles_flow_ebos+SPE3CASE1 (Failed)
```

**Comment by pgdr** [comment]
@GitPaean Can you print the stack trace?  I patched some `smspec_cmp` functionality in ecl yesterday.

**Comment by GitPaean** [comment]
I am fixing this PR.  It is not difficult.  `update_data` is not working properly for `flow` yet.

**Comment by GitPaean** [comment]
For the first failure. 
```
21: === Executing comparison for summary file ===
21: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe1/SPE1CASE2' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe1/opm-simulation-reference/flow_ebos/SPE1CASE2'.
21: Comparing 122 steps.
21: For keyword BPR:1
21: (days, reference value) and (days, check value) = (638, 6605.42) and (638, 6605.5)
21: The absolute deviation is 0.0810547. The tolerance limit is 0.02
21: The relative deviation is 1.22708e-05. The tolerance limit is 1e-05
21: Program threw an exception: [/home/kaib/OPM-devel-test/debug/opm-output/opm/test_util/summaryRegressionTest.cpp:116] Deviation exceed the limit.
21: 11 summary keyword(s) exhibit failures
21: 	 BPR:1
21: 	 	 Fails for: 98 / 122 steps.
21: 		 Largest absolute error: 6.044920e-01
21: 		 Largest relative error: 8.286410e-05
21: 	 BPR:1,1,1
21: 	 	 Fails for: 98 / 122 steps.
21: 		 Largest absolute error: 6.044920e-01
21: 		 Largest relative error: 8.286410e-05
21: 	 BPR:10,10,3
21: 	 	 Fails for: 95 / 122 steps.
21: 		 Largest absolute error: 1.480470e+00
21: 		 Largest relative error: 2.433330e-04
21: 	 BPR:300
21: 	 	 Fails for: 95 / 122 steps.
21: 		 Largest absolute error: 1.480470e+00
21: 		 Largest relative error: 2.433330e-04
21: 	 FOPR
21: 	 	 Fails for: 71 / 122 steps.
21: 		 Largest absolute error: 2.833980e+00
21: 		 Largest relative error: 1.503100e-04
21: 	 WBHP:INJ
21: 	 	 Fails for: 98 / 122 steps.
21: 		 Largest absolute error: 6.049800e-01
21: 		 Largest relative error: 8.017860e-05
21: 	 WBHP:PROD
21: 	 	 Fails for: 31 / 122 steps.
21: 		 Largest absolute error: 5.128910e+00
21: 		 Largest relative error: 1.208800e-03
21: 	 WGPR:PROD
21: 	 	 Fails for: 53 / 122 steps.
21: 		 Largest absolute error: 8.881250e+01
21: 		 Largest relative error: 9.873090e-04
21: 	 WGPT:PROD
21: 	 	 Fails for: 84 / 122 steps.
21: 		 Largest absolute error: 1.036400e+04
21: 		 Largest relative error: 1.843220e-04
21: 	 WOPR:PROD
21: 	 	 Fails for: 71 / 122 steps.
21: 		 Largest absolute error: 2.833980e+00
21: 		 Largest relative error: 1.503100e-04
21: 	 WOPT:PROD
21: 	 	 Fails for: 67 / 122 steps.
21: 		 Largest absolute error: 1.592000e+03
21: 		 Largest relative error: 3.079770e-05
21: === Executing comparison for restart file ===
21: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe1/SPE1CASE2' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe1/opm-simulation-reference/flow_ebos/SPE1CASE2'.
21: Comparing SEQNUM...done.
21: Comparing INTEHEAD...done.
21: Comparing LOGIHEAD...done.
21: Comparing DOUBHEAD...done.
21: Deviation results for keyword DOUBHEAD of type DOUB:
21: Average absolute deviation = 0
21: Median absolute deviation  = 0
21: Average relative deviation = 0
21: Median relative deviation  = 0
21: 
21: Comparing IWEL...done.
21: Comparing ZWEL...done.
21: Comparing OPM_XWEL...
21: Occurrence in first file    = 20
21: Occurrence in second file   = 20
21: Grid coordinate             = (1, 1, 1)
21: (first value, second value) = (2.264e+07, 2.26422e+07)
21: 
21: Program threw an exception: [/home/kaib/OPM-devel-test/debug/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
21: The absolute deviation is 2199.66, and the tolerance limit is 0.02.
21: The relative deviation is 9.71488e-05, and the tolerance limit is 1e-05.
21: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe1/SPE1CASE2' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe1/opm-simulation-reference/flow_ebos/SPE1CASE2'.
21: 
21: Common keywords for the two cases:
21: SEQNUM
21: INTEHEAD
21: LOGIHEAD
21: DOUBHEAD
21: IWEL
21: ZWEL
21: OPM_XWEL
21: OPM_IWEL
21: ICON
21: STARTSOL
21: PRESSURE
21: RS
21: RV
21: SGAS
21: SWAT
21: TEMP
21: ENDSOL
21: KRNSW_GO
21: KRNSW_OW
21: PCSWM_GO
21: PCSWM_OW
21: SOMAX
21: OPMEXTRA
21: 
21: Uncommon keywords for the two cases:
21: 
21: Failure for keyword OPM_XWEL
21: 	 Fails for 2 entries
21: 	 Largest absolute deviation: 3.193170e+02
21: 	 Largest relative deviation: 1.067960e-05
21: Failure for keyword PRESSURE
21: 	 Fails for 297 entries
21: 	 Largest absolute deviation: 5.493160e-02
21: 	 Largest relative deviation: 1.416900e-05
21: === Executing comparison for init file ===
```

**Comment by GitPaean** [comment]
The failure information for the second one. 
```
28: === Executing comparison for summary file ===
28: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe3/SPE3CASE1' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe3/opm-simulation-reference/flow_ebos/SPE3CASE1'.
28: Comparing 177 steps.
28: For keyword FOPR
28: (days, reference value) and (days, check value) = (104.286, 1035.72) and (156.429, 1034.2)
28: The absolute deviation is 1.52295. The tolerance limit is 0.02
28: The relative deviation is 0.00147042. The tolerance limit is 1e-05
28: Program threw an exception: [/home/kaib/OPM-devel-test/debug/opm-output/opm/test_util/summaryRegressionTest.cpp:116] Deviation exceed the limit.
28: 9 summary keyword(s) exhibit failures
28: 	 FOPR
28: 	 	 Fails for: 175 / 177 steps.
28: 		 Largest absolute error: 1.510660e+02
28: 		 Largest relative error: 1.000000e+00
28: 	 FOPT
28: 	 	 Fails for: 177 / 177 steps.
28: 		 Largest absolute error: 2.525620e+06
28: 		 Largest relative error: 1.000000e+00
28: 	 WBHP:INJ
28: 	 	 Fails for: 177 / 177 steps.
28: 		 Largest absolute error: 8.992260e+02
28: 		 Largest relative error: 1.000000e+00
28: 	 WBHP:PROD
28: 	 	 Fails for: 177 / 177 steps.
28: 		 Largest absolute error: 8.390420e+02
28: 		 Largest relative error: 1.000000e+00
28: 	 WGIR:INJ
28: 	 	 Fails for: 2 / 177 steps.
28: 		 Largest absolute error: 4.700000e+03
28: 		 Largest relative error: 1.000000e+00
28: 	 WGPR:PROD
28: 	 	 Fails for: 2 / 177 steps.
28: 		 Largest absolute error: 6.200000e+03
28: 		 Largest relative error: 1.000000e+00
28: 	 WOPR:PROD
28: 	 	 Fails for: 175 / 177 steps.
28: 		 Largest absolute error: 1.510660e+02
28: 		 Largest relative error: 1.000000e+00
28: 	 WOPT:PROD
28: 	 	 Fails for: 177 / 177 steps.
28: 		 Largest absolute error: 2.525620e+06
28: 		 Largest relative error: 1.000000e+00
28: 	 WWPR:PROD
28: 	 	 Fails for: 167 / 177 steps.
28: 		 Largest absolute error: 3.505310e+01
28: 		 Largest relative error: 1.000000e+00
28: === Executing comparison for restart file ===
28: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe3/SPE3CASE1' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe3/opm-simulation-reference/flow_ebos/SPE3CASE1'.
28: Comparing SEQNUM...done.
28: Comparing INTEHEAD...done.
28: Comparing LOGIHEAD...done.
28: Comparing DOUBHEAD...done.
28: Deviation results for keyword DOUBHEAD of type DOUB:
28: Average absolute deviation = 0
28: Median absolute deviation  = 0
28: Average relative deviation = 0
28: Median relative deviation  = 0
28: 
28: Comparing IWEL...done.
28: Comparing ZWEL...done.
28: Comparing OPM_XWEL...
28: Occurrence in first file    = 0
28: Occurrence in second file   = 0
28: Grid coordinate             = (1, 1, 1)
28: (first value, second value) = (2.27338e+07, 2.27334e+07)
28: 
28: Program threw an exception: [/home/kaib/OPM-devel-test/debug/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
28: The absolute deviation is 394.619, and the tolerance limit is 0.02.
28: The relative deviation is 1.73583e-05, and the tolerance limit is 1e-05.
28: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe3/SPE3CASE1' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe3/opm-simulation-reference/flow_ebos/SPE3CASE1'.
28: 
28: Common keywords for the two cases:
28: SEQNUM
28: INTEHEAD
28: LOGIHEAD
28: DOUBHEAD
28: IWEL
28: ZWEL
28: OPM_XWEL
28: OPM_IWEL
28: ICON
28: STARTSOL
28: PRESSURE
28: RS
28: RV
28: SGAS
28: SWAT
28: TEMP
28: ENDSOL
28: KRNSW_GO
28: KRNSW_OW
28: PCSWM_GO
28: PCSWM_OW
28: SOMAX
28: OPMEXTRA
28: 
28: Uncommon keywords for the two cases:
28: 
28: Failure for keyword OPM_XWEL
28: 	 Fails for 1 entries
28: 	 Largest absolute deviation: 9.616120e+01
28: 	 Largest relative deviation: 1.183740e-05
28: === Executing comparison for init file ===
28: Comparing '/home/kaib/OPM-devel-test/debug/opm-simulators-build/tests/results/flow_ebos+spe3/SPE3CASE1' to '/home/kaib/OPM-devel-test/debug/opm-simulators/../opm-data/spe3/opm-simulation-reference/flow_ebos/SPE3CASE1'.
28: Comparing INTEHEAD...done.
28: Comparing LOGIHEAD...done.
```

**Comment by atgeirr** [comment]
The clue to the second failure is:
```
28: (days, reference value) and (days, check value) = (104.286, 1035.72) and (156.429, 1034.2)
```
We are comparing different time points. We must either:
 - make the testing tool compare at the same time points, or
 - make the Dune 2.5 runs not chop the first timestep.

(Preferably both...)

**Comment by atgeirr** [comment]
> make the Dune 2.5 runs not chop the first timestep

Turns our that letting it take a few more nonlinear iterations is sufficient. Will not investigate further, but pass max_iter=15 (13 is the minimum required for this particular case) rather than the default 10 to the test run.

**Comment by atgeirr** [comment]
Having inspected both the SPE1 and SPE3 results, the Dune 2.5 well curves are spot on the old ones. So slackening the tolerances to make the 2.4 and 2.5 solutions accept each other as "close" should cause no  problems at all.

**Pull request closed without merging**
