### PR TITLE
make the reference Norne INIT files identical for flow_legacy and flow_ebos

### PR DESCRIPTION
**Pull request by andlaus**
this is the result of

```bash
cp norne/opm-simulation-reference/flow_legacy/NORNE_ATW2013.INIT norne/opm-simulation-reference/flow_ebos/NORNE_ATW2013.INIT
```

and is what was intended by #210.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
It looks like Jenkins did not even start for this. The PR builder for opm-data looks like it has not been run in a year, any idea what could be wrong @akva2?

I want this to be sorted out before merging!

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
there you go. sorry for all the noise and for being sloppy in my pr.

**Comment by atgeirr** [comment]
Thanks, will merge! BTW what did you change in the iterations above?

**Comment by akva2** [comment]
the jenkins setup. as you said, nobody had used this for a long time so it had some mould.

**Comment by atgeirr** [comment]
> the jenkins setup

But you did not change any of the modules' Jenkins scripts as far as I could see?

**Comment by akva2** [comment]
while i have tried to share as much of the jenkins setup as possible, and stick as much in git as possible, some small bits like git urls, and the call to those shared scripts needs to reside on jenkins.

**Comment by atgeirr** [comment]
OK, thanks for the explanation!

**Pull request merged**
