### PR TITLE
add reference data for msw_2D_H__

### PR DESCRIPTION
**Pull request by akva2**

### CODE REVIEW

**Comment by akva2** [comment]
@alfbr hope it's fine to add the data in this layout. we can reorganize how we want later. i would like to close this 'stage' in my work.

**Comment by alfbr** [comment]
Certainly, we can revisit folder structure and naming schemes at any time. Merging, thank you!

**Comment by akva2** [comment]
please hold merge, test failed for jenkins, need to investigate why.

**Comment by alfbr** [comment]
Holding off, feel free to self-merge when ready.

**Comment by atgeirr** [comment]
I assume this must be re-done due to changed simulator results and changed directory structure. Close or update?

**Comment by akva2** [comment]
this is long outdated, and was replaced by some other pr. sorry for not closing earlier!

**Pull request closed without merging**
