### PR TITLE
add a simplified version of the SPE1 dataset

### PR DESCRIPTION
**Pull request by andlaus**
the only remarkable aspect of this deck is that the current version of
the CPR preconditioner in opm-autodiff breaks down:

```
and@heuristix:~/src/opm-autodiff|master > ./bin/sim_fibo_ad deck_filename=../opm-data/simplespe1/SIMPLESPE1.DATA

================    Test program for fully implicit three-phase black-oil flow     ===============

---------------    Reading parameters     ---------------
deck_filename found at /, value is ../opm-data/simplespe1/SIMPLESPE1.DATA
strict_parsing not found. Using default value 'true'.
deck_filename found at /, value is ../opm-data/simplespe1/SIMPLESPE1.DATA
output not found. Using default value 'true'.
output_interval not found. Using default value '1'.
output_dir not found. Using default value '.'.
pvt_tab_size not found. Using default value '-1'.
sat_tab_size not found. Using default value '-1'.
threephase_model not found. Using default value 'gwseg'.
use_cpr not found. Using default value 'true'.
output not found. Using default value 'true'.
output_dir not found. Using default value 'output'.
output not found. Using default value 'true'.
output_vtk not found. Using default value 'true'.
output_dir not found. Using default value 'output'.
output_interval not found. Using default value '1'.

================ Starting main simulation loop ===============

---------------    Simulation step number 0    ---------------
      Current time (days)     0
      Current stepsize (days) 1
      Total time (days)       1216

dp_max_rel not found. Using default value '1e+09'.
ds_max not found. Using default value '0.2'.
drs_max_rel not found. Using default value '1e+09'.
relax_max not found. Using default value '0.5'.
max_iter not found. Using default value '15'.
relax_type not found. Using default value 'dampen'.

Iteration         Residual
        0        1.29402173
terminate called after throwing an instance of 'Dune::ISTLError'
Aborted
```

on the other hand, everything works fine if the CPR preconditioner is
not used:

```
and@heuristix:~/src/opm-autodiff|master > ./bin/sim_fibo_ad deck_filename=../opm-data/simplespe1/SIMPLESPE1.DATA use_cpr=false

================    Test program for fully implicit three-phase black-oil flow     ===============

---------------    Reading parameters     ---------------
deck_filename found at /, value is ../opm-data/simplespe1/SIMPLESPE1.DATA
strict_parsing not found. Using default value 'true'.
deck_filename found at /, value is ../opm-data/simplespe1/SIMPLESPE1.DATA
output not found. Using default value 'true'.
output_interval not found. Using default value '1'.
output_dir not found. Using default value '.'.
pvt_tab_size not found. Using default value '-1'.
sat_tab_size not found. Using default value '-1'.
threephase_model not found. Using default value 'gwseg'.
use_cpr found at /, value is 'false'.
linsolver not found. Using default value 'umfpack'.
output not found. Using default value 'true'.
output_dir not found. Using default value 'output'.
output not found. Using default value 'true'.
output_vtk not found. Using default value 'true'.
output_dir not found. Using default value 'output'.
output_interval not found. Using default value '1'.

================ Starting main simulation loop ===============

---------------    Simulation step number 0    ---------------
      Current time (days)     0
      Current stepsize (days) 1
      Total time (days)       1216

dp_max_rel not found. Using default value '1e+09'.
ds_max not found. Using default value '0.2'.
drs_max_rel not found. Using default value '1e+09'.
relax_max not found. Using default value '0.5'.
max_iter not found. Using default value '15'.
relax_type not found. Using default value 'dampen'.

Iteration         Residual
        0        1.29402173
        1      0.0614937239
        2    1.45760381e-05
Fully implicit solver took: 0.097702 seconds.

---------------    Simulation step number 1    ---------------
      Current time (days)     1
      Current stepsize (days) 14
      Total time (days)       1216

...
```

### CODE REVIEW

**Comment by atgeirr** [comment]
That is interesting. Have you figured out why it throws?

**Comment by andlaus** [comment]
it says "breakdown in BiCGStab" due to "h=0" which i think is weird because we use GMRES, right?

**Comment by andlaus** [comment]
By the way: Once we fixed the autodiff issue, I think that this dataset should be included into opm-data so that we don't get regressions on this front...

**Comment by atgeirr** [comment]
BiCGStab is used for solving the elliptic subsystem in the preconditioner. GMRES is used for the whole system.

**Comment by atgeirr** [comment]
There is no reason not to merge this as far as I can see, but we should wait until situation is resolved with  CPR before we add it to the automatic regression tests.

**Comment by andlaus** [comment]
> BiCGStab is used for solving the elliptic subsystem in the preconditioner. GMRES is used for the whole system.

I see.

>  There is no reason not to merge this as far as I can see, but we should wait until situation is resolved with CPR before we add it to the automatic regression tests.

agreed.

**Pull request merged**
