### PR TITLE
add a 300k cells version of the SPE1 problem

### PR DESCRIPTION
**Pull request by andlaus**
i.e., it provides a simple deck which is suitable for performance
comparisons.

### CODE REVIEW

**Comment by dr-robertk** [comment]
When running with ecl I get: 
 @--  ERROR  AT TIME        0.0   DAYS    (19-OCT-1982):
 @           UNRECOGNISED KEYWORD DZV      IN GRID DATA

**Comment by andlaus** [comment]
ok, that seems to be an Eclipse inconsistency: the RM says the DZV is for E300 only, in contrast to D[XY]V keywords which are also supported by E100. WTF?

anyway, I updated the deck to use DZ instead of DZV and also disabled most of the PRT output. could you please check again?

**Comment by dr-robertk** [comment]
Thx. The DZV problem is fixed. Now I get: 

 @--  ERROR  AT TIME        0.0   DAYS    (19-OCT-1982):
 @           THE NEW CONNECTION (  95  95  22) IN WELL PRODUCER  
 @           EXCEEDS MAXIMUM NUMBER OF CONNECTIONS PER WELL    1

**Comment by andlaus** [comment]
ok, thanks. that was another mistake of mine, this time it was the WELLDIMS keyword. hopefully fixed.

this file format is really not made to be hand edited by mere mortals like me...

**Comment by dr-robertk** [comment]
Now I get: 

 @--  ERROR  AT TIME        0.0   DAYS    (19-OCT-1982):
 @                 270000 VALUES NOT DEFINED IN BOX (  1-100,  1-100,  1- 30)
 @           OF KEYWORD DZ

**Comment by andlaus** [comment]
_arg_ in the previous fixup I mis-counted the number of zeros for the DZ keyword...

**Comment by andlaus** [comment]
BTW: the strange thing is that both, `Opm::UnstructuredGrid` and `Dune::CpGrid` accept a too short DZ keyword without producing an error or even a warning...

**Comment by dr-robertk** [comment]
Now it works. Thanks.

**Pull request merged**
