### PR TITLE
update reference results

### PR DESCRIPTION
**Pull request by andlaus**
OPM/opm-material#220 causes slight differences. @totto82 has looked at these differences and deemed them to be insignificant, though.

### CODE REVIEW

**Comment by andlaus** [comment]
I've updated this one to account for the latest ewoms master plus OPM/ewoms#182 and the latest version of OPM/opm-simulators#1019.

**Comment by andlaus** [comment]
oops. wrong PR. I'll come back to this in due time, sorry.

**Comment by atgeirr** [comment]
I guess this should be closed if it is replaced by #215?

**Comment by andlaus** [comment]
yes it should be closed for now, but no this is not succeeded by #215: this here updates the reference data due to OPM/opm-material#220. #215 updates the reference solutions because of OPM/opm-simulators#1019. Since I was confused I first used the branch for this PR for the update of for OPM/opm-simulators#1019, though.

So I'm closing this now. I'll open something when we deal with OPM/opm-material#220, maybe the update_data jenkins trigger even works now.

**Pull request closed without merging**
