### PR TITLE
update the UNSMRY file for the OPM reference solution

### PR DESCRIPTION
**Pull request by akva2**
this one changed because the current master only writes at the end of
each report step instead of at the end of each time step plus at the
end of each report step as it used to be. the curves seem to be
identical when ajusting for this, i.e. they touch at what seems to be
the end of report step.

the reference data is now hosted in a folder with the generic name
'OPM-reference-simulation'.

update plotwells.sh accordingly

### CODE REVIEW

**Comment by akva2** [comment]
jenkins run norne please

**Comment by andlaus** [comment]
the patch itself looks good IMO.

That said, I think the `plotwells.sh` script in its current form has only limited usefulness because it hardcodes its source files. wouldn't it be better to pass the source file names as command line arguments, i.e. changing the usage to `./plotwells.sh $FILE1 $FILE2` from `./plotwells.sh`?

**Comment by akva2** [comment]
probably, but right now i really don't have the time. if you want to look at it, please update run-norne.sh in opm-simulators accordingly.

@alfbr all good. merge at your leisure.

**Comment by andlaus** [comment]
> probably, but right now i really don't have the time. if you want to look at it, please update run-norne.sh in opm-simulators accordingly.

I'll do that, but only after 2016.04. (and if I don't forget. ;))

**Comment by alfbr** [comment]
Sure, thanks for the clean-up!

**Comment by atgeirr** [comment]
Just a question: exactly which version of the results did get merged now? The same that @andlaus posted?

**Comment by akva2** [comment]
Yes. Just put them in a different folder.

-------- Opprinnelig melding --------
Fra: Atgeirr Flø Rasmussen notifications@github.com
Dato: 21.04.2016 16:28 (GMT+01:00)
Til: OPM/opm-data opm-data@noreply.github.com
Ko: Arne Morten Kvarving Arne.Morten.Kvarving@sintef.no, Author author@noreply.github.com
Emne: Re: [OPM/opm-data] update the UNSMRY file for the OPM reference solution (#102)

Just a question: exactly which version of the results did get merged now? The same that @andlaushttps://github.com/andlaus posted?

**Pull request merged**
