### PR TITLE
Small python program for comparing two UNRST files - a small start

### PR DESCRIPTION
**Pull request by flikka**
This is mostly meant to show other contributors how we can do the comparison of output. Some input on what kind of data that makes sense to compare would be nice.

### CODE REVIEW

**Comment by andlaus** [comment]
I think at least the SGAS, SWAT, and PRESSURE fields in the UNRST file should be included, the rest is probably not too important...

different question: how can this script be used? do I need to compile ERT with python bindings and shared libraries enabled and add the lib directory of the install directory to LD_LIBRARY_PATH?

**Comment by joakim-hove** [comment]
> [....] do I need to compile ERT with python bindings and shared libraries enabled 

Yes.

> and add the lib directory of the install directory to LD_LIBRARY_PATH?

Yes; and also add the `${CMAKE_INSTALL_PREFIX}/python` path to your `$PYTHONPATH` variable.

**Comment by flikka** [comment]
I´ll add a README with some "practical instructions", and some help. Also incorporate Joakims suggestions. As for the variables, when using PRESSURE there is a massive (unit-problem-lookalike) difference, I´ll get back on that one. Thanks.

**Comment by andlaus** [comment]
that difference is probably because OPM always uses METRIC when it writes the UNRST files (regardless of the unit system used by the input deck), while the input deck specifies FIELD which is what is used by eclipse, I suppose...

**Comment by joakim-hove** [comment]
that difference is probably because OPM always uses METRIC when it writes

> the UNRST files (regardless of the unit system used by the input deck),
> while the input deck specifies FIELD which is what is used by eclipse, I
> suppose...

I actually fear that OPM writes unconverted - i.e. SI units.

Jaokim

**Comment by andlaus** [comment]
> I actually fear that OPM writes unconverted - i.e. SI units.

If it did not regress, then EclipseWriter uses bars for pressure. (I'm pretty sure about this, because it came with plenty of headaches...)

**Comment by bska** [comment]
> I actually fear that OPM writes unconverted - i.e. SI units.

If the values are off by a factor of about 14.5, then it's bars vs. psi.  If the values are off by a factor of 100,000 (100e3), then it's bars vs. Pa.  If the values are off by a factor of about 1.45e3, then it's psi vs. Pa.  Anything else requires further investigation.

**Comment by andlaus** [comment]
I just checked: the ratio is about 14.5. I cannot be entirely sure about it because I did not find out how to find out the range of a value in a single time step in ResInsight...

**Comment by flikka** [comment]
That's swift feedback guys! I can also confirm that about 14.5 is the factor by which we are off. Is this a kind of missing feature, or a bug? Recommendations?

**Comment by alfbr** [comment]
I believe the simulation code will need to honour the units requested by the input file. Unless somebody steps up and takes on the task now, I suggest the factor is corrected for when the comparison is made (that is, in the python script). Then we can update the test once we have correct units from the simulator.

It is great to see this coming together, thanks for the great work! My apologies for still having to challenge the technical solution. I imagine that SPE\* are to be considered integration tests, and as such should be implemented as tests, including a comparison to a reference solution. This would remove the need for pyhton bindings with dependencies, and may also remove the need for the Eclipse output files (although comparing output files may be an important part of the test actually). However, it will require more effort than the current solution, so I believe getting this up and running now was the right thing to do. Thoughts on this are welcome.

**Comment by totto82** [comment]
> That's swift feedback guys! I can also confirm that about 14.5 is the factor by which we are off. Is this a kind of missing feature, or a bug? Recommendations?

I will say this is a missing feature. It would be beneficial if OPM and Eclipse writes out in the same units. It will ease the comparison a lot.

**Comment by joakim-hove** [comment]
> My apologies for still having to challenge the technical solution.

Well - it is of course valid to raise questions to the technical solution, but when something new comes about like this I think we must be careful not to search so much for perfection that we fail to recognize something which is good here and now. 

> I imagine that SPE\* are to be considered integration tests, and as such should be implemented as tests ...

I don really understand what you mean; what is uploaded here is (ECLIPSE) reference data and a script for comparision; i.e. necessary ingredients for a test. When it comes to ECLIPSE versus OPM reference data I see value in both.

> This would remove the need for pyhton bindings with dependencies, and may also remove the need for the Eclipse output files ....

Python aside I think the use of ECLIPSE binary output files in the testing is essential; when it comes to 'eating-the-dogfood' we are not very good in the OPM community, as illustrated by the pressure scaling in the current example.

**Comment by flikka** [comment]
HI @alfbr 

> My apologies for still having to challenge the technical solution.

It has not quite caught my radar that you have challenged the solution - let't take a separate discussion about this. My motivation for using the python/ERT way - is that ERT has features for reading the Eclipse output.

> and may also remove the need for the Eclipse output files (although comparing output files may be an important part of the test actually)

I do not quite understand this - this test is motivated by the wish to compare OPM results to Eclipse results, how should we do this without using Eclipse output files?

**Comment by alfbr** [comment]
> I do not quite understand this - this test is motivated by the wish to compare OPM results to Eclipse results, how should we do this without using Eclipse output files?

I believe the test is primarily to ensure that OPM simulates and reports the flow and production correctly within reasonable bounds, not that it is equal to Eclipse. Testing the output writer could be done separately.

> I think the use of ECLIPSE binary output files in the testing is essential

This is a good point. We need tests that ensures correct output, and this supports comparing output binaries.

**Comment by andlaus** [comment]
problem solved, see OPM/opm-parser#301 and OPM/opm-core#651

**Comment by flikka** [comment]
Nice @andlaus, that made all the difference. Thanks.

**Comment by flikka** [comment]
In my head this is ok for now, if you have other objections, please voice :-) Thanks.

**Comment by andlaus** [comment]
to me it now looks good as well...

**Pull request merged**
