### PR TITLE
Added restart version of SPE1CASE2.DATA for test purpose

### PR DESCRIPTION
**Pull request by chflo**
Added restart version of SPE1CASE1.DATA, - SPE1CASE1_RESTART.DATA for test purpose.
Will be used from a unittest on autodiff. 
The following keywords are added to SPE1CASE1_RESTART.DATA: SKIPREST, RESTART and UNIFIN.

### CODE REVIEW

**Comment by alfbr** [comment]
Please note the CASE1 is not supported by OPM due to lack of support for DRSDT. Maybe basing it on CASE2 is better?

Other than that, the file looks good, and I am happy to merge. Last thing though, have you tested that the restarting works with both Eclipse and Flow?

**Comment by chflo** [comment]
I can change to SPE1CASE2 if that is ok ?
The restart file written/read by OPM currently contains an OPM specific keyword OPM-XWEL so restart with OPM can only be done from restart files written by OPM.

**Comment by alfbr** [comment]
Yes, please base it on CASE2 instead. Ideally we should follow the file format, which means the restart should work with Eclipse rather than introducing custom keywords. However, this is work in progress, so I will merge once it is based on CASE2.

**Comment by alfbr** [comment]
Thank you! Please aim to remove the need for custom keyword in the near future. Merging.

**Comment by joakim-hove** [comment]
> Ideally we should follow the file format, which means the restart should work with Eclipse rather than introducing custom keywords.

Of course we agree on what is ideal; however I fear it is quite long into the future before you can have your cake and eat it to. The problem is the state of wells; in Eclipse that is stored in "keywords" `IWEL`, `XWEL` and `SWEL` - the content/structure of these keywords is undocumented - it is therefor virtually impossible to read/write the well state in format which Eclipse understands.

**Comment by alfbr** [comment]
Thanks for the information! However, you seem to argue for Eclipse restarting Flow or vice versa, I am simply stating that we should try to avoid custom keywords.

**Comment by joakim-hove** [comment]
> However, you seem to argue for Eclipse restarting Flow or vice versa, I am simply stating that we should try to avoid custom keywords.

Well - my argument is that since we can currently not provide correct values for the `XWEL` keyword we are better off with using a custom keyword, i.e. `OPM-XWEL`. If we had used the ordinary `XWEL` name we would have created a false illusion of Eclipse <-> Flow restart capabilities.

**Comment by alfbr** [comment]
Ah, I misunderstood, it is a keyword in the binary file, not the input deck. Then I rest my case, this is the right solution at the current stage. Thank you!

**Pull request merged**
