### PR TITLE
update reference data for  spe3 spe5 spe9 spe9group

### PR DESCRIPTION
**Pull request by jenkins4opm**
Reason: https://github.com/OPM/opm-simulators/pull/1341

libecl         = b4f6dfe270077690ca9bd9ce8c201a1db7a9c99d
opm-common     = c55885633ce2427e85caa3f5956d5ee1e9dbe4fd
opm-core       = d049125205758693c66cd94533ddeb690acc285b
opm-grid       = b23869face5f04db614bca284e08c8bd4f2d14e0
opm-material   = 3c5c35ca4fcd16def56a25cbaee81eefde816e37
opm-parser     = dc1b6763a26ad0fb964dee187d89960750baa49c
opm-output     = b7f79205e5aca150bc1a98137c574c2365628e9e
ewoms          = f0b72e63bf0e9e54ec170d730642692490fb2698
opm-simulators = 5e5c2557db85d6df944c591aca2deb43413ad5d5

### CODE REVIEW

**Comment by GitPaean** [comment]
I think we should remove .PRT and maybe other txt files from the `update_data` or the reference results, since we might not compare them.

**Comment by akva2** [comment]
i've said the same before but it was shot down.

**Comment by totto82** [comment]
I think this should be merged asap since it makes all other tests fail. Can someone with permission merge it?

**Comment by atgeirr** [comment]
> Can someone with permission merge it?

I'm sorry but I do not understand what is really going on. Which PR to read...?

**Comment by atgeirr** [comment]
OK, I get it after discussion with @totto82. Must rerun jenkins in OPM/opm-simulators#1341 to verify that it actually fixes master. Will merge when that is green.

Since all other jenkins tasks will fail because master is broken, I have stopped all other ongoing jenkins tasks.

**Pull request merged**
