### PR TITLE
Restructure polymer simple2D test

### PR DESCRIPTION
**Pull request by akva2**
To make it compatible with regression testing scripts.

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
@akva2 denne feiler, er det pga ert->libecl mon tro?

**Comment by akva2** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by akva2** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by akva2** [comment]
not related to ert -> ecl but bugs i introduced making the run triggers avail everywhere. sorry for the noise, but it takes some adjustments and i cannot test it 'offline'

**Comment by akva2** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by akva2** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by akva2** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by atgeirr** [comment]
jenkins run polymer opm-simulators=1182 please

**Comment by akva2** [comment]
this will fail i believe due to the reference file (i think some code disabling output of fields has landed after i generated them). also we need to remember to update opm-parser.

**Comment by atgeirr** [comment]
Ok, I stopped the job.

**Comment by akva2** [comment]
the best way to proceed would be to merge this to get the restructuring (need the opm-parser merge at the same time), then run 1182 with update_data to update.

**Comment by akva2** [comment]
will prepare the opm-parser pr.

**Comment by atgeirr** [comment]
> the best way to proceed would be to merge this to get the restructuring (need the opm-parser merge at the same time), then run 1182 with update_data to update.

But will that break Jenkins in the meantime? I *don't* want to break Jenkins...

**Comment by akva2** [comment]
okay, if that's not acceptable i will create files locally. the only consequence is that you will likely get a polymer update included next time some other file need updates.

**Comment by atgeirr** [comment]
But will merging just this + opm-parser PR  (not opm-simualtors 1182) break Jenkins, making it useless for other PR merges?

(If only run_polymer breaks that is ok.)

**Comment by akva2** [comment]
i will just fail for the polymer test until data is updated. as in builds will be marked as unstable but it will not affect the other tests. it will also temporarily hamper the run polymer integration test.

**Comment by atgeirr** [comment]
> i will just fail for the polymer test until data is updated.

What polymer test? In opm-parser? As of yet there are no opm-simulator polymer tests.

**Comment by akva2** [comment]
ehm yes. 1178 adds the test. sorry for being unclear. the only effect on *existing tests* is that the run trigger will fail. this runs  post-commit on opm-simulators so we may see some failed builds there.

**Comment by atgeirr** [comment]
Then I'm fine with merging this (and opm-parser) first, and use update_data from 1178!

**Comment by atgeirr** [comment]
jenkins build this opm-parser=1072 with downstreams please

**Pull request merged**
