### PR TITLE
SPE3 dataset

### PR DESCRIPTION
**Pull request by flikka**
Fetched from the E-room - using the _MODIFIED version, with two more modifications (ALL and BPRES removed).

Running this dataset with sim_fibo_ad, gives approx 2% deviations on the pressure, and some more (8%) on the saturations.

### CODE REVIEW

**Comment by bska** [comment]
Just out of curiosity: Why do we need the `.CFG` file?

**Comment by joakim-hove** [comment]
> Just out of curiosity: Why do we need the .CFG file?

No one I guess; I suggest we cut back the ECLIPSE result to the files `EGRID, INIT, UNRST, UNSMRY, SMSPEC` and `PRT` files.

**Comment by bska** [comment]
> I suggest we cut back the ECLIPSE result to the files [specific list]

I'd also add the `.RSSPEC` to that list, mostly for future development, but otherwise I agree.

**Comment by totto82** [comment]
> Running this dataset with sim_fibo_ad, gives approx 2% deviations on the pressure, and some more (8%) on the saturations. 

I am a bit surprised that the deviations are so large. Especially for the saturations. What does 8 % deviation mean? Is this an average over each cell deviation?

**Comment by flikka** [comment]
@bska and @joakim-hove Agreed - my lack of knowledge about the Eclipse data just resulted in adding'em all. Will follow your suggestions.

@totto82 - The 8% deviation, sorry for being unprecise - that means essentially that the maximum deviation for the saturations (SGAS/SWAT) was 0.08. Most are not that high, but the current comparison uses an "acceptable deviation", and I had to set it up to 0.08 to make it pass for the saturations.

**Comment by andlaus** [comment]
stupid question: are these 8% the difference of the saturations or the ratio?

**Comment by andlaus** [comment]
(I mean deviation of the ratio from 1...)

**Comment by flikka** [comment]
Ok - checked again now, so some data. Sorry if I'm unclear about the definition of deviation (can of course look in the code though...):

For SPE3, an example (always nice with examples) is:

```
Number of report steps for keyword SGAS in spe3/eclipse-simulation/SPE3_MODIFIED.UNRST: 26
Error: SGAS value in files EclFile: spe3/eclipse-simulation/SPE3_MODIFIED.UNRST and EclFile: spe3/opm-simulation/SPE3_MODIFIED.UNRST in report step 19, active cell number 51 does not match: 0.834403693676 != 0.764267444611
```

So - in report step 19, the cell number 51 have these two values for SGAS. I'm simply taking one minus the other (apply some absoluteness), and then compare to a threshold. In this case the deviation is 0.0701 or something along those lines.

Hope it is more clear now.

**Comment by alfbr** [comment]
Thanks for the explanation, it means you are setting a threshold using uniform norm. For cases like SPE3 the deviation seems too high. Maybe somebody can comment whether we have seen this kind of deviation on a cell by cell basis all along? In any case, it means that being able to compare Eclipse and OPM from the binary output files is very valuable for many of us, so it really is great to see the file input and output support coming together.

Moving over to more complex cases like Norne, I don't think the uniform norm makes sense. Simply because the only thing preventing extreme cells is the use of MINPV. Even with MINPV I believe we should expect some cells to be hit hard by deviations that are insignificant. Using a weighted L² (or Euklidean if you take the discrete view) norm may be more relevant here.

**Comment by totto82** [comment]
Thanks Kristian for the clear explanation. I am able to reproduce the same difference. But luckily I already have a fix that removes it. (Now the max deviation should be 0.0016) See PR OPM/opm-autodiff#200

**Comment by flikka** [comment]
Thanks @totto82 and @alfbr 

Regarding "how to compare" - thanks for suggestions, and I hope we'll revisit them when we start adding Norne simulation comparison to the "automated pipeline".

**Comment by andlaus** [comment]
I think there's not much controversy left with this PR. I'll merge. Thanks @flikka

**Pull request merged**
