### PR TITLE
Spe9_new created files

### PR DESCRIPTION
**Pull request by lkerrand**
These are the created files with Corner Point Grid that allow a very good match between Eclipse and Flow for SPE9

### CODE REVIEW

**Comment by alfbr** [comment]
Thanks for the great work! This seems to be exactly what we need. Just a few minor changes to clean up a bit:
-Remove the files GRDECL.ods and F_CPG_SPE9.DATA
-Rename E_CPG_SPE9.DATA to SPE9_CP.DATA
-Rename TOPSVALUES.DATA to TOPSVALUES_CP.INC, and update SPE9_CP.DATA to the new file name
-Move everything except PERMVALUES.DATA to the spe9 folder
-Remove the spe_new folder with PERMVALUES.DATA

**Comment by totto82** [comment]
I am currently working on a fix so that the well-transmissibilities are correctly calculated.  Expect a PR very soon. I suggest using the original input for the wells to make SPE9.DATA and SPE9_CP.DATA as similar as possible.

**Comment by alfbr** [comment]
Great, then defaults for item 8 in COMPDAT should be used in the new deck too.

**Comment by totto82** [comment]
A minor comment:  In SPE9.DATA the name of the producers are PRODU\* and in SPE9_CP.DATA they are PROD*. 

Eclipse and flow match using SPE9_CP.DATA and OPM/opm-core#881

**Comment by lkerrand** [comment]
OK, all changes have been made. The TOPVALUES file has been removed because it is not necessary with CP geometry. Wells are named PRODU for simplification.

**Comment by alfbr** [comment]
Thanks! Merging.

**Pull request merged**
