### PR TITLE
This commit i contains Bg modififcation : 

### PR DESCRIPTION
**Pull request by lkerrand**
because of units problem, problems, previous values entered were wrong.

The data file for Corner Point Geometry has been added because it is the only that Flow manage to run with the modified tuning file.
For tuning, the run on Eclipse last 1 min and probably more than 5 days fon Flow, neveertheless, increasing timestep.control.targetiteration and control.max_timestep_in_days seems to bring improvements.

As I fixed all problems late and that my stay at Statoil end today, I had no time to complete a Flow run and upload the results.

### CODE REVIEW

**Comment by lkerrand** [comment]
This was my last pull request. Farewell opm-commuinity, it was a pleasure to work with you !
I wish you the best !

**Comment by andlaus** [comment]
we hope that you enjoyed your stay with us, and we even hope that you enjoyed it so much so much that you'll answer the occasional questions for stuff which was originally done by you. (you don't need to be affiliated with Statoil for this, it is an open source project after all :))

Anyway, so long and thanks for the fish!

**Comment by alfbr** [comment]
Thank you for the correction, it is good to see that we honour the publication. Enabling flow to run by using a supported grid format is also welcome. Merging.

**Comment by bska** [comment]
This change, for some reason, breaks opm-autodiff's `flow` utility on `SPE9_CP.DATA`.

**Comment by bska** [comment]
> This change, for some reason, breaks opm-autodiff's flow utility on `SPE9_CP.DATA`.

On closer inspection, the SPE 9 grid is significantly altered in this PR.

### Before PR #82

before-82

### After PR #82

after-82

**Comment by GitPaean** [comment]
Here? 

```
22,694  spe9/SPE9.GRDECL
12,660 additions, 10,034 deletions not shown
```

**Comment by bska** [comment]
> Here?

Yes, that's the change in question.  Granted, the `flow` utility should not crash in this case--it's a bug in `flow` that it does--but the grid is in any case no longer consistent with the well placements in the simulation scenario.

**Comment by alfbr** [comment]
My apologies, I did not realise that this PR affected SPE9. It should not touch SPE9, I will revert this change ASAP.

**Pull request merged**
