### PR TITLE
added: norne well plots can now plot flow and flow_ebos results

### PR DESCRIPTION
**Pull request by akva2**
also pass path to summary.x instead of expecting it in $PATH

### CODE REVIEW

**Comment by andlaus** [comment]
jenkins run norne_ebos please

**Comment by andlaus** [comment]
nice!

**Comment by akva2** [comment]
... i am running tests already. luckily i never added the ebos job here ;)

**Comment by andlaus** [comment]
ok, I'll merge right now, then...

**Comment by akva2** [comment]
lol. devil and the details... i said i was *running* tests. i've tested locally so it should be okay, but chill on the trigger-happyness in the future ;)

**Comment by andlaus** [comment]
yeah, the patch looks fine and it "only" affects jenkins. for such things, I'm even more trigger happy than usual ;). if there turns out to be a problem, it can be fixed another PR, IMO.

**Comment by akva2** [comment]
sure, but time it worse and you had destroyed my test run because the pr is gone.

**Pull request merged**
