### PR TITLE
Adding two reduced norne cases. 

### PR DESCRIPTION
**Pull request by GitPaean**
This is a start of the uploading of reduced Norne cases. 

I had a bad time in deciding the cases to upload, since with time many of the old cases do not make sense anymore. They happened to help to understand the Norne case at the very beginning.

NORNE_C5_3P_EQUIL_RSRV.DATA is the most important one for the past month, with live gas and live oil and with other proper designs. 

NORNE_C5_3P_EQUIL_RSRV.DATA

```
Grid/petroprops: Norne with all except: FAULTS, FAULTMULT, FLUXNUM, MULTREGT, MINPV, minor grid adjustment (ACTNUM away disconnected block) that is probably unnecessary.
Also commented out MULTZ_JUN_05_MOD.INC for local barriers.
Fluids: Norne fluid, but 1 region
Wells: 2 injection wells, 3 producers (NOT original SCHEDULE).
Time span of Simulation: 2000 days run.

The faults should be easily added and kind of tested before. 
```

NORNE_C5_3P_EQUIL.DATA

```
Similar to NORNE_C5_3P_EQUIL_RSRV.DATA except using dead gas and dead oil with some hand-made PVDO and PVDG. 
```

### CODE REVIEW

**Comment by dr-robertk** [comment]
I ran the NORNE_C5_3P_EQUIL.DATA and it runs through. The only thing I had to remove from the deck was the keyword ALL.

**Comment by andlaus** [comment]
> The only thing I had to remove from the deck was the keyword ALL.

I could not find this keyword in the manual, so it may be an artefact? (on the other hand it appears in the example on page 1261, so it may be just undocumented. how I love that file format!)

**Comment by qilicun** [comment]
In this reduced Norne case, we need to compare OPM and ECLIPSE, there are many properties need to compare, so I just add `ALL` to `SUMMARY` section, let ECLIPSE output as much properties as possible.

**Comment by GitPaean** [comment]
@dr-robertk, Please also test the NORNE_C5_3P_EQUIL_RSRV.DATA file, which includes live gas and live oil and is more important.

**Comment by dr-robertk** [comment]
I tested both cases, both run through without problems. I can add my param file, if needed. 
Next thing will be the comparison with ecl.

**Comment by andlaus** [comment]
> In this reduced Norne case, we need to compare OPM and ECLIPSE, there are many properties need to compare, so I just add ALL to SUMMARY section, let ECLIPSE output as much properties as possible.

please leave this PR as-is (i.e., with the keyword in the deck): it is a valid keyword and even seems to be widely used. We need to fix this in opm-parser...

**Comment by totto82** [comment]
I could not find a README file for this deck. It would be beneficial to know exactly what is "reduced" in this case. The commit tells me something, but not all. For instance is the fluid properties the same as the original? Is all grid/trans modifiers included etc.

**Comment by totto82** [comment]
> I could not find a README file for this deck. It would be beneficial to know exactly what is "reduced" in this case. The commit tells me something, but not all. For instance is the fluid properties the same as the original? Is all grid/trans modifiers included etc.

I found the information in Atgeirr email "final norne testing". If you could add the same info in a README file that would have been great.

**Comment by GitPaean** [comment]
Added a readme file.

**Comment by GitPaean** [comment]
Yeah. Corrected.

**Comment by totto82** [comment]
Thanks. I believe this PR is ready for merging. I have tested it, and the results matches Eclipse beautifully.

**Pull request merged**
