### PR TITLE
update the OPM reference solutions for the SPE3 cases

### PR DESCRIPTION
**Pull request by andlaus**
this should fix the failed jenkins test.

### CODE REVIEW

**Comment by atgeirr** [comment]
Yay! Thanks, will merge (testing this PR will consist of watching Jenkins after the fact...)

**Comment by atgeirr** [comment]
Seems that Jenkins did not like this, or (perhaps more likely) did not update properly. Let's not revert this though (unless we find it is really at fault).

**Comment by andlaus** [comment]
hm. this may also be a python problem of the comparison script, because it says

```
Traceback (most recent call last):
  File "output_comparator/src/compare_eclipse.py", line 147, in <module>
    main( eclipse_file_location , opm_file_location ,  base_name , rel_tolerance, abs_tolerance)
  File "output_comparator/src/compare_eclipse.py", line 127, in main
    compareRestartFiles(eclipse_restart_file, opm_restart_file, rel_tolerance, abs_tolerance)
  File "output_comparator/src/compare_eclipse.py", line 85, in compareRestartFiles
    comparison_data_sgas = compareRestarts(eclipse_restart_file, opm_restart_file, "SGAS")
  File "output_comparator/src/compare_eclipse.py", line 79, in compareRestarts
    result_data = compareValuesForKeyword(restart_file_A, restart_file_B, comparison_data, keyword)
  File "output_comparator/src/compare_eclipse.py", line 48, in compareValuesForKeyword
    findDeviationsThroughAllReportSteps(absolute_deviations, relative_deviations, restart_file_A, restart_file_B, keyword)
  File "output_comparator/src/compare_eclipse.py", line 16, in findDeviationsThroughAllReportSteps
    B_values_in_step_i = ecl_kw_list_B[report_step]
IndexError: list index out of range
```

unfortunately I don't know how to get this script...

**Comment by andlaus** [comment]
my stupid. I was tripped by a typo. looking at the script it seems like the number of report steps is different. weird.

**Pull request merged**
