### PR TITLE
change symlink to hardcopy

### PR DESCRIPTION
**Pull request by akva2**
upcoming changes will make the init files differ for flow_legacy
and flow_ebos, thus we need dedicated copies

ref https://github.com/OPM/opm-simulators/pull/1019

### CODE REVIEW

**Comment by andlaus** [comment]
this PR should not change anything? if yes and if there are no objections, I'll merge it soon.

**Comment by andlaus** [comment]
> this PR should not change anything?

I mean "should not change anything for now and w.r.t. the reference files that are used by the tests"

**Comment by akva2** [comment]
No functional changes just preparatory for having different files. Merge whenever

**Comment by andlaus** [comment]
this does not seem controversial, let it go in!

**Comment by atgeirr** [comment]
The INIT file added here is *not* identical to the flow_legacy file it used to be a soft link to, obviously that was not intended.

This broke the entire Jenkins chain... Please run Jenkins before merging! @andlaus will you fix this by replacing the not-identical copy with an identical copy?

**Comment by andlaus** [comment]
@atgeirr: here you go: #213

**Pull request merged**
