### PR TITLE
Use Equil for initialization

### PR DESCRIPTION
**Pull request by totto82**
The SPE3 and SPE9 decks are changed such that EQUIL is used to initialize the cases. 

The RSVD keyword is used in SPE9 to set the RS values instead of the PBVD keyword. 

With this change SPE3 and SPE9 runs, converges within 15 non-linear iterations and reproduces Eclipse results.

### CODE REVIEW

**Comment by totto82** [comment]
The convergence failure lately for SPE3 and SPE9 is caused by a change introduced with the time-stepping control. Previously the simulator just moves to the next time step whenever convergence fails. As reported in  #16 there were convergence issues on SPE3 (and also on SPE9 for some of the time steps). Changing the initialization somewhat fixes this. An alternative fix is to increase the limit for non-linear iterations to 25. I think this instability in the convergence behavior needs a closer look.

**Comment by GitPaean** [comment]
Just something FYI and I hope it can help a little bit. It might not be that accurate in term of the numbers while it should be fairly true. 

The convergence of the Newton iterations has been always tricky in some sense. There are something happened we can explain while not easy for some other things. 

For the first time step of SPE3, there has been a little convergence problem after we introduced the oscillation treatment. At the first beginning, it could get convergent within 15 iterations even some oscillations happened (within something like 11 or 12 iterations). After we introduced oscillation treatment, due to the relaxation, the required iteration number was increased to be 14 or was increased to 17 sometime later, bigger than 15. (The relaxation treatment slows down the convergence a little bit and OPM/opm-autodiff#200 seems to slow down the convergence a little bit too)

For the second last time step of SPE3, the convergence problem was introduced after the OPM/opm-autodiff#200 , which improves the results of SPE3 against Eclipse. Our current oscillation treatment could not solve this problem and it could not get convergent within 100 or 200 iterations, which I think means it will not get convergent no matter how many iterations we run. I did not observe OPM/opm-autodiff#200 made any other instability problems else where. SPE3 has always been more challenging in getting convergent than SPE1 and SPE9. 

I did not observe any convergence problem of SPE9 at the time of #16 . It should be something later.

**Comment by totto82** [comment]
This PR should not be merged until we get a better grasp on what's causes the convergence problem in the first place. We may find something that also helps on the convergence on the Norne case

**Comment by atgeirr** [comment]
I think this has been resolved now, at least spe1/3/9 run for me with default parameters and data files as present in the current master of opm-data. So can we close this @totto82?

**Comment by andlaus** [comment]
> I think this has been resolved now, at least spe1/3/9 run for me with default parameters and data files as present in the current master of opm-data. So can we close this @totto82?

I think the point of this is to use EQUIL init instead of explicit initial conditions via PRESSURE, SWAT, SGAS and RS. SPE-9 uses the latter at the moment. I guess which of the two methods is perferred is mostly a matter of taste because as long as both options are covered by some dataset, there's no real issue. (EQUIL init is already excercised by the Norne dataset, while explicit values are used for SPE1...)

**Comment by alfbr** [comment]
Actually, I am not sure we can keep this SPE3 deck, please consider basing it on the new one.

**Pull request closed without merging**
