### PR TITLE
Add SPE1 with SLGOF instead of SGOF

### PR DESCRIPTION
**Pull request by totto82**
This PR adds a modified SPE1 where SLGOF is used instead of SGOF

### CODE REVIEW

**Comment by andlaus** [comment]
ok, I have verified that flow produces produce exactly the same result this and the SGOF version. 

(to do this, the satfunc_refactoring branches of opm-{core,autodiff} are currently required, and the SLGOF PRs need to be merged into opm-{parser,material}, but it seems that the deck itself is correct, so that this PR here should be merged.)

One thing which I cannot check is whether the Eclipse results are identical. did you verify this @totto82?

**Comment by totto82** [comment]
Eclipse and OPM differs quite a bit on SPE1CASE1.DATA. What I have verified is that Eclipse produces the same results when using SPE1CASE1.DATA and SPE1CASE1_SLGOF.DATA.(and SPE1CASE1_FAMII.DATA)

**Comment by andlaus** [comment]
> What I have verified is that Eclipse produces the same results when using SPE1CASE1.DATA and SPE1CASE1_SLGOF.DATA.(and SPE1CASE1_FAMII.DATA)

ok, cool. I'm now quite confident that Everything Is Correct (TM)...

**Comment by alfbr** [comment]
This seems like a good deck for integration testing, merging. Thanks!

**Pull request merged**
