### PR TITLE
Add RESV + Solvent test case

### PR DESCRIPTION
**Pull request by totto82**

### CODE REVIEW

**Comment by akva2** [comment]
if this is intended for a opm-simulators test, the folder layout needs adjustment.

**Comment by totto82** [comment]
Would /spe1case2_solvent_resv work?

**Comment by akva2** [comment]
yes. the point is that the scripts expects a directory layout opm-data/&lt;case name&gt;/&lt;specified datafile&gt;, e.g. https://github.com/OPM/opm-simulators/blob/master/compareECLFiles.cmake#L168

a test name of 'solvent_test_suite' is a bit too generic, in particular this is also used for the commit messages generated by the update-data script https://github.com/OPM/opm-simulators/blob/master/tests/update_reference_data.sh#L23

**Comment by totto82** [comment]
Would this work?

**Comment by akva2** [comment]
yep, perfect

**Comment by andlaus** [comment]
opm-data is not used for regression testing anymore. closing.

**Pull request closed without merging**
