### PR TITLE
Adding test case for summary vectors.

### PR DESCRIPTION
**Pull request by cfbe**
I created this simple test case which contains a range of different summary vectors, since it is needed for testing out summary-plot functionality in ResInsight. Note that this test-case does not work with OPM-flow.

### CODE REVIEW

**Comment by atgeirr** [comment]
Good, will merge!

**Comment by alfbr** [comment]
I believe this merge was pre-mature, this case probably do qualify for a parsing test. Please consider adding it:
https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/IntegrationTests/CMakeLists.txt#L16

**Comment by cfbe** [comment]
The test-cases do contain LGR (in addition to aquifer and fault). Can you clarify if that is supposed to be supported by the parser?

**Comment by alfbr** [comment]
I just briefly looked through the case and didn't notice. Just forget my comment then.

**Pull request merged**
