### PR TITLE
adding a example for group control based on SPE9

### PR DESCRIPTION
**Pull request by GitPaean**
.UNRST file is about 69MB, and I got a warning from github when pushing the branch. Should I remove this file?

And I am not sure about the current suggestion of the directory structure. Please suggest.

### CODE REVIEW

**Comment by akva2** [comment]
can you reduce the number of report steps ?

**Comment by GitPaean** [comment]
I can, then we need someone else to provide the reference result, which is okay to me.

**Comment by jokva** [comment]
That's because git isn't a particularly good fit technology-wise for this (frequently updated large binary files).

**Comment by GitPaean** [comment]
I reduced the number of the report steps. @totto82 , could you please update the eclipse reference for this example.

**Comment by totto82** [comment]
Looks good. We can add reference solution later if this becomes a test.

**Pull request merged**
