### PR TITLE
Updated SPE1CASE2 and SPE3CASE1 opm-simulation-references

### PR DESCRIPTION
**Pull request by kristfho**
The opm-simulation-reference of SPE1CASE2 and SPE3CASE1 have been updated. In addition the keyword `INIT` have been added to the `SPE1CASE2.DATA` and `SPE3CASE1.DATA` file, to produce `.INIT` files.

opm-common: hash `bd425bfff9fefdaf270922e820c59ecc3d5306e4`
opm-parser: hash `d6f49971c8c6e7cf6a96d2cec9f36bfc7e508891`
opm-material: hash `44fe774cfe69ae47d7952c4329df2e6cc3d8b4d1`
opm-output: hash `f9bd01228233844e8925b9764e000de6a5285a94`
opm-core: hash `bc0977ec3dc52940450b0c346e44937f65ba5ed7`
opm-grid: hash `7e7748903ca789cdfa160346db15b32e8085c285`
opm-simulators: hash `afa64d98759ec25a096acb80d6c588fc58ed1646`

### CODE REVIEW

**Comment by flikka** [comment]
I think some of the opm-reference restart (UNRST) files are now "wrong". Currently, flow (or opm-output) seems to append report steps, so unless you delete the file between simulations, you get an ever increasing number of report steps in the file. The SPE1CASE2.UNRST file now seems to contain 360 steps, whereas the correct is 120. 

This (and the fact that opm-output now appends) causes quite some confusion.

**Comment by alfbr** [comment]
Nice catch, thanks for reporting! We really should get this bug fixed.

**Comment by jokva** [comment]
> I think some of the opm-reference restart (UNRST) files are now "wrong". Currently, flow (or opm-output) seems to append report steps, so unless you delete the file between simulations, you get an ever increasing number of report steps in the file. The SPE1CASE2.UNRST file now seems to contain 360 steps, whereas the correct is 120. 

This is true. There's a patch up that fixes the immediate issue, but with some fundamental shortcomings. It's not ready for upstream.

**Comment by kristfho** [comment]
A new PR with the correct file is now created.

**Pull request merged**
