### PR TITLE
adding seveal 3D polymer examples.

### PR DESCRIPTION
**Pull request by GitPaean**
adding a few 3D examples with PLYSHLOG shear calculation. 

The 3D grid is generated with MRST and the fluid property is from Norne. 

@qilicun , could you help to upload the Eclipse reference results with a separate PR? Please use Eclipse 2013, since the shear model is a 2013 version. We can change to the new version when Eclipse 2015 is there.  Thanks.

### CODE REVIEW

**Comment by GitPaean** [comment]
Please hold not merging the examples now. Some tweaking is on-going to make the example better in demonstrating the simulator.

**Comment by qilicun** [comment]
@GitPaean 

I have test these data with Eclipse, but the error happened.

`INSUFFICIENT DATA TO COMPUTE Y TRANSMISSIBILITIES`

Do you know what's the reason?

**Comment by GitPaean** [comment]
I do not have any idea. OPM did not report anything wrong so far. Maybe you can check or send a .PRT file to me?

**Comment by qilicun** [comment]
@GitPaean 

I think you probably make a mistake in your `INCLUDE/PERMY.inc`, in this file the first line should be `PERMY`?

**Comment by GitPaean** [comment]
Thanks. Possibly. I updated a little bit yesterday, could you please try the updated ones. Maybe you can begin with the one no-shear. Please still use the 2013.2 version.

**Comment by GitPaean** [comment]
And we need to test later why it works for the OPM, while not working for the Eclipse. Maybe there is something wrong there.

**Comment by GitPaean** [comment]
Done tweaking. It is ready to get merged from my side.

**Comment by GitPaean** [comment]
Will someone will be able to review this PR? If it is not the correct place to put the examples, please let me know. Thanks.

**Comment by atgeirr** [comment]
Can you review this, @qilicun?

**Comment by qilicun** [comment]
I Just have one comment, please use all upper case for the deck file name, because eclipse is sensitive to that, if not, eclipse will not run... If you could fix this, the PR can be merged,

In general I think this PR is good, except the comment above. Thanks for your effort @GitPaean !

 I also did the comparison with ECLIPSE, the results look good, after this PR is merged, I will submit another PR  for eclipse reference.

**Comment by GitPaean** [comment]
done updating. Thanks for the comment.

**Comment by qilicun** [comment]
Thanks, I think it's time to push the green button. @atgeirr

**Pull request merged**
