### PR TITLE
updating the 2d polymer example with more features.

### PR DESCRIPTION
**Pull request by GitPaean**

### CODE REVIEW

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by GitPaean** [comment]
This data needs https://github.com/OPM/opm-simulators/pull/1342 to work. But I do not understand the failure was from compilation. Does it mean the master branch was broken?

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by GitPaean** [comment]
Compilation error again. Any idea about how this happened?

**Comment by bska** [comment]
> Compilation error again. Any idea about how this happened?

Did you do local build tests both **with** and **without** MPI.  The error seems to suggest something MPI-related.
```
opm/autodiff/ParallelDebugOutput.hpp: In member function 'virtual bool Opm::ParallelDebugOutput<Dune::CpGrid>::collectToIORank(const Opm::SimulationDataContainer&, const Opm::WellStateFullyImplicitBlackoil&, const Opm::data::Solution&, int)':
opm/autodiff/ParallelDebugOutput.hpp:645:77: error: no matching function for call to 'Opm::WellsManager::WellsManager(const Opm::EclipseState&, const int&, int, const int*, const int*, int, Dune::cpgrid::Cell2FacesContainer, Opm::UgGridHelpers::FaceCentroidTraits<Dune::CpGrid>::IteratorType, const Opm::DynamicListEconLimited&, bool, std::unordered_set<std::__cxx11::basic_string<char> >)'
                                            std::unordered_set<std::string>());
```

**Comment by GitPaean** [comment]
The following code in `ParallelDebugOutput.hpp`
```
610                 WellsManager wells_manager(eclipseState_,                                                                                
611                                            schedule_,
612                                            wellStateStepNumber,                                                                          
613                                            Opm::UgGridHelpers::numCells( globalGrid ),                                                   
614                                            Opm::UgGridHelpers::globalCell( globalGrid ),                                                 
615                                            Opm::UgGridHelpers::cartDims( globalGrid ),                                                   
616                                            Opm::UgGridHelpers::dimensions( globalGrid ),                                                 
617                                            Opm::UgGridHelpers::cell2Faces( globalGrid ),                                                 
618                                            Opm::UgGridHelpers::beginFaceCentroids( globalGrid ),                                         
619                                            dynamic_list_econ_limited,                                                                    
620                                            false,
621                                            // We need to pass the optionaly arguments                                                    
622                                            // as we get the following error otherwise                                                    
623                                            // with c++ (Debian 4.9.2-10) 4.9.2 and -std=c++11                                            
624                                            // converting to ‘const std::unordered_set<std::basic_string<char> >’ from initializer list would use explicit constructor
625                                            std::unordered_set<std::string>());    
``` 

could not be compiled, while it does not report compilation error locally.

**Comment by GitPaean** [comment]
> Did you do local build tests both with and without MPI. The error seems to suggest something MPI-related.

My local building is always with MPI.

**Comment by GitPaean** [comment]
My local building looks like broken, while from  different place.  I will investigate it locally first and report back with a fresh rebuilding.

**Comment by bska** [comment]
> The following code in `ParallelDebugOutput.hpp`
> ```
> 610                 WellsManager wells_manager(eclipseState_,                                                                                
> 611                                            schedule_,
> 612                                            wellStateStepNumber,
>  ...
```

That's not the code that did not compile.  The error message I quoted said "no matching call to"

```C++
Opm::WellsManager::WellsManager(const Opm::EclipseState&, /* 1 */
    const int&, /* 2 */
    int, /* 3 */
    const int*, /* 4 */
    const int*, /* 5 */
    int, /* 6 */
    Dune::cpgrid::Cell2FacesContainer, /* 7 */
    Opm::UgGridHelpers::FaceCentroidTraits<Dune::CpGrid>::IteratorType, /* 8 */
    const Opm::DynamicListEconLimited&, /* 9 */
    bool, /* 10 */
    std::unordered_set<std::__cxx11::basic_string<char> >) /* 11 */
```

but you're passing 12 arguments.  Possibly a mismerge somewhere.

**Comment by GitPaean** [comment]
jenkins build this with downstreams please

**Comment by GitPaean** [comment]
> but you're passing 12 arguments. Possibly a mismerge somewhere.

My local building turned out to be okay. I mean that code in the `ParallelDebugOutput.hpp` should not be compiled, while it compiles locally on my machine while Jenkins reported error.

**Comment by GitPaean** [comment]
Sorry. That code should be okay. I forgot there is a `WellsManager_impl.hpp` besides the `.cpp` file.

**Comment by bska** [comment]
> I mean that code in the `ParallelDebugOutput.hpp` should not be compiled, while it compiles locally on my machine while Jenkins reported error.

Sorry, I don't really understand what you're trying to say here.  For whatever reason, when Jenkins attempts to build this PR (#277) the net result is that we're trying to pass 11 arguments to a function that expects 12 parameters.  That's probably a mismerge somewhere--especially in light of PR OPM/opm-parser#1138.

**Comment by GitPaean** [comment]
> Sorry, I don't really understand what you're trying to say here. For whatever reason, when Jenkins attempts to build this PR (#277) the net result is that we're trying to pass 11 arguments to a function that expects 12 parameters.

You are right. even the line number is different. Jenkins is using a different version of the code from my local machine for some reason unclear to me at the moment.

**Comment by GitPaean** [comment]
Not sure if there is any useful information in the following, especially `Your branch is behind 'origin/master' by 387 commits, and can be fast-forwarded.`


```
Building in workspace /var/lib/jenkins/workspace/opm-data-PR-builder
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/OPM/opm-simulators # timeout=10
Fetching upstream changes from https://github.com/OPM/opm-simulators
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/OPM/opm-simulators +refs/*:refs/remotes/origin/*
 > git rev-parse origin/master^{commit} # timeout=10
Checking out Revision 9db16ad9dca64eff083e4b4af6dc145b70e21198 (origin/master)
Commit message: "Merge pull request #1342 from GitPaean/fixing_polymer"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9db16ad9dca64eff083e4b4af6dc145b70e21198
First time build. Skipping changelog.
[opm-data-PR-builder] $ /bin/bash /tmp/jenkins6836502672970881890.sh
Removing deps/
Removing mpi/
From https://github.com/OPM/opm-simulators
 * branch              master     -> FETCH_HEAD
Previous HEAD position was 9db16ad9... Merge pull request #1342 from GitPaean/fixing_polymer
Switched to branch 'master'
Your branch is behind 'origin/master' by 387 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Trigger is now jenkins build this with downstreams please opm-data=277
sha1 is now master
~/workspace/opm-data-PR-builder ~/workspace/opm-data-PR-builder
```

**Comment by bska** [comment]
>
```
Your branch is behind 'origin/master' by 387 commits, and can be fast-forwarded.
```

It's likely to be at least somewhat related to the build issue.  However, I don't know enough about the specifics of the `update_data` command word to say if this is a property of the (opm-data) PR, or if it is something else.  Maybe @akva2 can shed some light on the matter?

**Comment by akva2** [comment]
my bad. bug in the opm-data code and it is used so seldom that it hasn't been caught before now. it checked out 'master' rather than 'origin/master' for opm-simulators which means it was stuck on whichever state was sitting in the local master branch (which was old).

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Pull request merged**
