### PR TITLE
Added OPM reference solutions for Norne

### PR DESCRIPTION
**Pull request by joakim-hove**
We are currently in the process of creating a set of scripts to automate build and run Norne, which typically will be invoked from Jenkins. The purpose of this will be to simplify the test that a set of PR's give the same result on Norne.

To facilitate this we need to manage a Norne reference solution. This PR adds such a solution.

### CODE REVIEW

**Comment by alfbr** [comment]
Are these intended to replace the reference solutions from Eclipse? This may be a good idea, since we are in a position to start trusting our own results on the Norne data-set. I will merge.

**Comment by andlaus** [comment]
note that these files will change once flow does not write everything twice per timestep. (On a different note, an additional goodie of the only-write-once-per-timestep changes, which I suppose @alfbr in particular is happy about, is that output writing is accelerated by a factor of two...)

**Comment by joakim-hove** [comment]
> Are these intended to replace the reference solutions from Eclipse? 

My plan was that they should serve as an alternative to those from Eclipse, but yes - replacement is also an option.

**Comment by atgeirr** [comment]
> replacement is also an option.

I'd say we should keep comparing to eclipse until it becomes impractical or impossible for some reason (likely many years from now).

**Comment by jokva** [comment]
> note that these files will change once flow does not write everything twice per timestep. (On a different note, an additional goodie of the only-write-once-per-timestep changes, which I suppose @alfbr in particular is happy about, is that output writing is accelerated by a factor of two...)

For automated testing we're more interested in summary-type results and totals, but the reference solution would obviously have to be kept up-to-date with simulator output.

**Comment by andlaus** [comment]
> For automated testing we're more interested in summary-type results and totals, but the reference solution would obviously have to be kept up-to-date with simulator output.

yeah: the well totals soon will be reduced to 1/2 of the summary files in this PR and the writing performance will also improve because currently it is not possible in `flow` to disable writing UNRST files altogether (maybe this should be hacked in?!)...

**Comment by jokva** [comment]
Would that make the results differ?

**Comment by andlaus** [comment]
the well totals

**Pull request merged**
