### PR TITLE
Use two perforations in the wells

### PR DESCRIPTION
**Pull request by totto82**
The wells in the original SPE3 perforates two cells each. With these changes the SPE3 converge at all time steps and the results matches Eclipse.

### CODE REVIEW

**Comment by atgeirr** [comment]
Good, I'll merge this tomorrow if no-one complains. Just one question: I notice EQLDIMS is being un-commented, is this because a) we require it now, or b) we don't require it but manage to safely ignore it. I hope it is b)...

**Comment by andlaus** [comment]
I am a bit surprised: why are the results different if wells perforate only one cell while they are the same if two are perforated? Are the previous Eclipse results for a deck which is different from the one used by OPM so far or does Eclipse automatically extend the perforations?

**Comment by totto82** [comment]
The results do not change much,  if anything. But increasing the number of perforations improves the convergence. Or more specific, the reason for the convergence problem is that the condition in cell 49, the layer one cell above the production well, oscillates between having oil and not in the 23 time step.  In one iteration oil is condensed, then in the next the oil saturation is negative.  

What is worrying me is that both MRST and Eclipse seems to tackle the situation with one perforation. The well treatment in MRST is somewhat different that in OPM, especially in how inactive wells are treated. For instance MRST stops the producer in some iterations, due to backflow/crossflow. I.e the producer wants to inject instead of produce.

**Comment by totto82** [comment]
> b) we don't require it but manage to safely ignore it. I hope it is b)...

It is b). I can comment it out again if you want that.

**Comment by atgeirr** [comment]
> It is b). I can comment it out again if you want that.

No need, it is better to keep the deck closer to the original.

**Comment by atgeirr** [comment]
I'll merge this, but we should keep in mind the problem exposed by the one-perforation-per-well variant.

**Comment by andlaus** [comment]
> The results do not change much, if anything.

does this mean that Eclipse converges just fine with a single perforation and OPM doesn't?

**Comment by totto82** [comment]
> does this mean that Eclipse converges just fine with a single perforation and OPM doesn't?

Yes, it does.

**Comment by andlaus** [comment]
> Yes, it does.

that's a bit weird on the OPM side, isn't it?

**Comment by totto82** [comment]
> that's a bit weird on the OPM side, isn't it?

Yes it is. And I have spent the last days trying to understand this, but without fully succeeding. I think, we need to revisit this again. But as this "luckily" is not a problem with the original SPE 3, I suggest we wait.

**Pull request merged**
