### PR TITLE
Added OPM reference data to spe3 folder. To be used for regression testi...

### PR DESCRIPTION
**Pull request by flikka**
Rerun of the SPE3 case, data added. Will start using the python script for comparison on Jenkins, so that the comparsion OPM-OPM-reference test is done in the same way as the OPM-Eclipse test.. See http://80.240.129.131:8080/view/SPE%20Tests/job/SPE3-OPM-OPM%20Regression/

### CODE REVIEW

**Comment by flikka** [comment]
I did include the text output too, but I'm not using it. Should it be skipped in the repo?

**Comment by joakim-hove** [comment]
> Should it be skipped in the repo?

In my opinion yes.

**Comment by andlaus** [comment]
> > Should it be skipped in the repo?
> 
> In my opinion yes.

I concur if you add a python script to compare UNSMRY files...

**Comment by flikka** [comment]
Ok - I'll leave them for now then, until a summary comparison is in place.

**Pull request merged**
