### PR TITLE
update spe regression test data

### PR DESCRIPTION
**Pull request by akva2**
cause: https://github.com/OPM/opm-output/pull/98

### CODE REVIEW

**Comment by atgeirr** [comment]
This makes the tests in opm-simulators (compareECLFiles_SPE1CASE2, compareECLFiles_SPE3CASE1, compareECLFiles_SPE9_CP_SHORT) succeed for me. They used to fail, and I did not fix it since I misunderstood the cause (I now believe the cause was that I had not updated opm-data in a while), but they go through now.

I therefore think this should be merged, unless @akva2 wants to add some more changes first?

**Comment by akva2** [comment]
i ran into unexpected issues on the ci server that i'm currently targeting. please hold.

**Comment by joakim-hove** [comment]
Merging - as suggested by @akva2 [here](https://github.com/OPM/opm-output/pull/114#issuecomment-255728355).

**Comment by alfbr** [comment]
It would be nice with commit hashes.

**Comment by akva2** [comment]
They are there (commit not pr description). Formatting was off so i just removed from desc rather than fixing.

**Comment by alfbr** [comment]
There they are, thanks!

**Pull request merged**
