### PR TITLE
Added case SPE1CASE2_ACTNUM_RESTART.

### PR DESCRIPTION
**Pull request by joakim-hove**
The DATA file is an exact copy of the SPE1CASE2_ACTNUM case, but the
RESTART keyword has been inserted in the SOLUTION section.

To be used for testing of restart capabilities.

### CODE REVIEW

**Comment by alfbr** [comment]
Thank you, this will improve testing. I am ready to merge, but one question first. Would it make sense to have one (or a few if there are incompatible features) tailored deck for to test against? For example, one deck named SPE1CASE2_TESTS, or something more descriptive.

**Comment by joakim-hove** [comment]
> Would it make sense to have one (or a few if there are incompatible features) tailored deck for to test against?

I don't fully understand what you mean; but in the sense that the different `SPE1` decks in opm-data are starting to become a bit messy I assume I agree. My suggestion would be to have two top level directories:

```
spe1/ 
spe1_testcases/
```

Where the `spe1/` directory contains only one complete `SPE1` dataset used for normal simulations - this would also be the case which was most interesting for users not directly involved in opm development. The `spe1_testcases/` would contain various perturbed varieties of the `SPE1` dataset - where the main purpose was to test features like e.g. restarting flow?

**Comment by jokva** [comment]
His point is if that two tests can use the same data set (but focus on different aspects) because the configuration in question aren't incompatible, it would be much easier to have just one (or a handful) of variations.

If you add restart to the SPE1CASE2_ACTNUM, will the other tests break? If no, I suggest just adding the restart keyword to the ACTNUM deck (and maybe rename it slightly).

**Comment by joakim-hove** [comment]
> His point is if that two tests can use the same data set (but focus on different aspects) because the configuration in question aren't incompatible, it would be much easier to have just one (or a handful) of variations.

OK - that is a good point; but I actually think we are still adhering to that principle.

> [...] If no, I suggest just adding the restart keyword to the ACTNUM deck (and maybe rename it slightly).

A restart based integration test like:
1. Run flow from step 0 to S2 - leaving a valid restart file behind.
2. Start flow as a restart from step S1 < S2 and run to S2.
3. Compare the solution after alternatives 1) and 2)

actually requires two separate decks. So unless we go beyond Eclipse and e.g. support a `--restart` commandline switch[1], or alternatively modify the decks as part of the test, I see no alternative to having both the `xxx.DATA` and `xxx_RESTART.DATA` varieties.

[1]: Which I actually think is a good idea

**Comment by jokva** [comment]
> actually requires two separate decks.

It's settled then.

**Pull request merged**
