### PR TITLE
prune the old files for testing

### LINKED ISSUE #313: Reference results should be pruned
The reference results for the integration tests have been moved to the new opm-tests repository and they thus do not serve any useful purpose within opm-data anymore. In conjunction with the fact that they are the reason why cloning opm-data takes so long (cf https://www.youtube.com/watch?time_continue=1&v=r1hL1lvwG9c ), I am of the considerate opinion they should bite the dust and the history of opm-data should be rewritten so that these files no longer need to be downloaded when cloning the repository.

### PR DESCRIPTION
**Pull request by andlaus**
this resolves #313. it does not yet cleanup the git history (and thus does not reduce repository size) because fiddling with history is only possible via a direct push. I'll do this once this PR gets merged.

### CODE REVIEW

**Comment by andlaus** [comment]
@akva2, @alfbr, @atgeirr: is anything which prevents pressing the green button?

**Comment by akva2** [comment]
i can't help you as i need an okay from the repo owner.

**Comment by alfbr** [comment]
Thanks for the effort! Merging.

**Comment by andlaus** [comment]
thanks for merging. I tried to prune the history, but for this I need rights to force-push to this repository. if you want to see how the repository wiill look after the prune, see here:

https://github.com/andlaus/opm-data/tree/WIP

(by far the biggest files in it are the SPE10 decks. if I made no mistake the branch still is less than 25 MB to download.)

**Comment by andlaus** [comment]
ok: I uploaded a full pruned-only version of opm-data at https://github.com/andlaus/opm-data-pruned . The short story is that only 25 MB need to be downloaded to clone it while it ships all data sets provided current opm-data repo with history. (@alfbr: I lack permissions to adapt the "real" repository, so you probably need to do this yourself.)

**Comment by alfbr** [comment]
Thanks, will try to get it in.

**Comment by andlaus** [comment]
@alfbr: any news on this front? it would be nice to have a reasonably sized repo for the OPM 2018.10 release.

**Comment by andlaus** [comment]
@albr: what's the status here? I thought this was wanted for 2018.10?

**Comment by alfbr** [comment]
Sorry, time fell short. Maybe we can do a hangout to get it sorted?

**Pull request merged**
