### PR TITLE
change: reorganize multisegment well test

### PR DESCRIPTION
**Pull request by akva2**
moving into a directory layout matching the other models,
which are compatible with external scripting.

also adds reference data for the test.

### CODE REVIEW

**Comment by joakim-hove** [comment]
I know the love of Travis is unevenly distributed - but it is not just a toy; this merge broke one of the tests in opm-parser for no good reason?!

**Comment by GitPaean** [comment]
Looks like the directory needs to be updated after this PR.

**Comment by atgeirr** [comment]
> this merge broke one of the tests in opm-parser for no good reason?!

It was done in support of OPM/opm-simulators#949. I was not aware of this breaking a test, even though it had a jenkins run and I did a local check (I probably forgot to run all tests and just did the opm-simulators tests). Sorry about that!

**Comment by joakim-hove** [comment]
No big deal - my point was just that there was a quite clear red cross on it - clicking on that it was equally clear that the PR broke a test in opm-parser.

**Pull request merged**
