### PR TITLE
Full NORNE model with a few minor changes (listed below)

### PR DESCRIPTION
**Pull request by dr-robertk**
COPY
  FLUXNUM MULTNUM /
/
has been added to make the MULTREGT keyword work.
In the file INCLUDE/PETRO/FLUXNUM_0704.prop the keyword fluxnum has been changed to FLUXNUM.

The lines
INCLUDE
'./INCLUDE/PETRO/E3.prop' /

have been uncommented, i.e. E3 is included.

I removed the file BC0407_HIST01122006.SCH~ since it was a backup file for
BC0407_HIST01122006.SCH.

Currently this deck runs (with the timestepcontrol) until 143 days where it seg faults because of the issues discussed in  issue #219 (opm-autodiff).

### CODE REVIEW

**Comment by andlaus** [comment]
> In the file INCLUDE/PETRO/FLUXNUM_0704.prop the keyword fluxnum has been changed to FLUXNUM.

the effect of the lower-case keyword could be that Eclipse does in fact silently ignore it. does anybody know more about this? (i.e., is Eclipse case-insensitive in fact?)

**Comment by dr-robertk** [comment]
The deck also runs with eclipse now after two small fixes. There is another small issue. That is that the 
COPY 
  FLUXNUM MULTNUM /
/
trick actually causes eclipse to fail with an error. What should we do about this?

**Comment by atgeirr** [comment]
While I do not understand why the COPY operation fails with eclipse, it is not a reason to hold off merging this. If you discover a bug or workaround, please update the case.

**Comment by totto82** [comment]
- While I do not understand why the COPY operation fails with eclipse

FLUXNUM was not capitalized when it was included earlier on. That's the reason Eclipse didn't swallow it I guess.

**Comment by andlaus** [comment]
> FLUXNUM was not capitalized when it was included earlier on. That's the reason Eclipse didn't swallow it I guess. 

since COPY did not work, this probably means that Eclipse ignores lower-case keywords? i.e., we should remove the `fluxnum` keyword from the deck instead of capitalizing it?

**Comment by totto82** [comment]
- since COPY did not work, this probably means that Eclipse ignores lower-case keywords? i.e., we should remove the fluxnum keyword from the deck instead of capitalizing it?

Or just that COPY is sensitive to cases. I.e. FLUXNUM MULTNUM / is different COPY fluxnum MULTNUM / . I can test this later today

**Comment by andlaus** [comment]
> Or just that COPY is sensitive to cases. I.e. FLUXNUM MULTNUM / is different COPY fluxnum MULTNUM / .

_arg_ right. The closer you look, the more bizarre it gets...

**Comment by totto82** [comment]
It seems neither of our assumptions were right. It seems that Eclipse uses FLUXNUM in MULTREGT if MULTNUM is not specified.

 KEYWORD MULTNUM  FOLLOWING COPY  
 IS NOT VALID FOR THIS RUN  
 CHECK THE OPTIONS IN RUNSPEC " 

And for the copying part: Eclipse gives the following error msg:
 KEYWORD MULTNUM  FOLLOWING COPY  
 IS NOT VALID FOR THIS RUN  
 CHECK THE OPTIONS IN RUNSPEC 

I did try to change GRIDOPTS in RUNSPEC without luck.

**Comment by andlaus** [comment]
does this mean that we should remove the misspelled FLUXNUM keyword and be happy?

**Pull request merged**
