### PR TITLE
Change ORAT keyword to RESV.

### PR DESCRIPTION
**Pull request by dr-robertk**
This PR changes all ORAT keywords to RESV when the flowrate (?) is non zero.

### CODE REVIEW

**Comment by atgeirr** [comment]
Is this a change back to the original state of the deck?

**Comment by dr-robertk** [comment]
Maybe @totto82 could comment on that. He suggested the change.

**Comment by totto82** [comment]
Yes, it is. According to the log @andlaus changed all RESV to ORAT to make it run long time ago.

**Comment by atgeirr** [comment]
Good, will merge then!

**Pull request merged**
