### PR TITLE
Change comparison method for the restart comparisons (SGAS, SWAT, PRESSURE)

### PR DESCRIPTION
**Pull request by flikka**
Changed from just counting deviations above this and that, to rather calculate average and median deviations. I think this is more interesting. The main program still uses a threshold to determine success or failure (0 or 1 exit status), but this is now based on the average and median values.

Look to the bottom of http://80.240.129.131:8080/job/SPE1-OPM-ECLIPSE-comparison/77/console to see how the new output / functionality looks.

### CODE REVIEW

**Comment by atgeirr** [comment]
This change is probably very good, and since I am no Python expert I will assume it is perfect. Just a few clarifications:
- This replaces one file with lots of other files. Is that just a reorganisation (apart from the behaviour change you described)?
- There is a new test/ directory. Is that unit testing for the components of the comparator?
- Where are the actual values used for the comparison thresholds placed? In the Jenkins script?
- Have you verified that the existing Jenkins tests pass as before with this change?

**Comment by flikka** [comment]
Hi @atgeirr, thanks for the feedback, adressing your points below.
- The compare_eclipse.py file has changed quite a bit (and moved into a src folder). The comparison used to be "cell-by-cell between dataset A and B" - and if _one_ value was outside the specified threshold, we got a "failure".

Now the comparison is "cell-by-cell between A and B", as before, but now the comparison data are averaged, medianed etc++, and results stored in an object, comparison_data. My thought is that this comparison_data can be expanded as we go - storing other values, all deviations for all cells (if somebody wants that), other types of data (summary data) etc.

So a reorganization, and some different features.
- The two other extra files are unit tests, put in the "tests" folder - as you suggest. There was one left over from the old version - you made me realize that, thanks.
- Regarding the thresholds - they are as you suggest put in the Jenkins script. 
- I have set up the SPE1 Eclipse vs OPM autodiff job against my branch (http://80.240.129.131:8080/job/SPE1-OPM-ECLIPSE-comparison), to test that "it works". The SPE3 and 9 are planned to be changed too, but currently they don't run so I was planning on waiting until they start running again.

**Comment by atgeirr** [comment]
> The SPE3 and 9 are planned to be changed too, but currently they don't run so I was planning on waiting until they start running again.

I'll leave it to you to merge this whenever you think the time is right, then.

**Comment by flikka** [comment]
Thanks

**Pull request merged**
